namespace FlatData;

enum CVCollectionType : int
{
    CVNormal = 0,
    CVEvent = 1,
    CVEtc = 2,
}

enum Nation : int
{
    None = 0,
    All = 1,
    JP = 2,
    GL = 3,
    KR = 4,
}

table CharacterVoiceExcel {
    character_voice_unique_id:long;
    character_voice_group_id:long;
    voice_hash:uint;
    only_one:bool;
    priority:int;
    display_order:long;
    collection_visible:bool;
    c_v_collection_type:CVCollectionType;
    unlock_favor_rank:long;
    localize_c_v_group:string;
    nation:[Nation];
    volume:[float];
    delay:[float];
    path:[string];
}

root_type CharacterVoiceExcel;