// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace FlatData
{

public enum AccountState : int
{
  WaitingSignIn = 0,
  Normal = 1,
  Dormant = 2,
  Comeback = 3,
  Newbie = 4,
};


}
