// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace FlatData
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct BGMRaidExcel : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static BGMRaidExcel GetRootAsBGMRaidExcel(ByteBuffer _bb) { return GetRootAsBGMRaidExcel(_bb, new BGMRaidExcel()); }
  public static BGMRaidExcel GetRootAsBGMRaidExcel(ByteBuffer _bb, BGMRaidExcel obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public BGMRaidExcel __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long StageId { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public long PhaseIndex { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public long BGMId { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }

  public static Offset<FlatData.BGMRaidExcel> CreateBGMRaidExcel(FlatBufferBuilder builder,
      long StageId = 0,
      long PhaseIndex = 0,
      long BGMId = 0) {
    builder.StartTable(3);
    BGMRaidExcel.AddBGMId(builder, BGMId);
    BGMRaidExcel.AddPhaseIndex(builder, PhaseIndex);
    BGMRaidExcel.AddStageId(builder, StageId);
    return BGMRaidExcel.EndBGMRaidExcel(builder);
  }

  public static void StartBGMRaidExcel(FlatBufferBuilder builder) { builder.StartTable(3); }
  public static void AddStageId(FlatBufferBuilder builder, long stageId) { builder.AddLong(0, stageId, 0); }
  public static void AddPhaseIndex(FlatBufferBuilder builder, long phaseIndex) { builder.AddLong(1, phaseIndex, 0); }
  public static void AddBGMId(FlatBufferBuilder builder, long bGMId) { builder.AddLong(2, bGMId, 0); }
  public static Offset<FlatData.BGMRaidExcel> EndBGMRaidExcel(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<FlatData.BGMRaidExcel>(o);
  }
}


static public class BGMRaidExcelVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*StageId*/, 8 /*long*/, 8, false)
      && verifier.VerifyField(tablePos, 6 /*PhaseIndex*/, 8 /*long*/, 8, false)
      && verifier.VerifyField(tablePos, 8 /*BGMId*/, 8 /*long*/, 8, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
