// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace FlatData
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct CharacterStatsTransExcel : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static CharacterStatsTransExcel GetRootAsCharacterStatsTransExcel(ByteBuffer _bb) { return GetRootAsCharacterStatsTransExcel(_bb, new CharacterStatsTransExcel()); }
  public static CharacterStatsTransExcel GetRootAsCharacterStatsTransExcel(ByteBuffer _bb, CharacterStatsTransExcel obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public CharacterStatsTransExcel __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public FlatData.StatType TransSupportStats { get { int o = __p.__offset(4); return o != 0 ? (FlatData.StatType)__p.bb.GetInt(o + __p.bb_pos) : FlatData.StatType.None; } }
  public FlatData.EchelonExtensionType EchelonExtensionType { get { int o = __p.__offset(6); return o != 0 ? (FlatData.EchelonExtensionType)__p.bb.GetInt(o + __p.bb_pos) : FlatData.EchelonExtensionType.Base; } }
  public int TransSupportStatsFactor { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public FlatData.StatTransType StatTransType { get { int o = __p.__offset(10); return o != 0 ? (FlatData.StatTransType)__p.bb.GetInt(o + __p.bb_pos) : FlatData.StatTransType.SpecialTransStat; } }

  public static Offset<FlatData.CharacterStatsTransExcel> CreateCharacterStatsTransExcel(FlatBufferBuilder builder,
      FlatData.StatType TransSupportStats = FlatData.StatType.None,
      FlatData.EchelonExtensionType EchelonExtensionType = FlatData.EchelonExtensionType.Base,
      int TransSupportStatsFactor = 0,
      FlatData.StatTransType StatTransType = FlatData.StatTransType.SpecialTransStat) {
    builder.StartTable(4);
    CharacterStatsTransExcel.AddStatTransType(builder, StatTransType);
    CharacterStatsTransExcel.AddTransSupportStatsFactor(builder, TransSupportStatsFactor);
    CharacterStatsTransExcel.AddEchelonExtensionType(builder, EchelonExtensionType);
    CharacterStatsTransExcel.AddTransSupportStats(builder, TransSupportStats);
    return CharacterStatsTransExcel.EndCharacterStatsTransExcel(builder);
  }

  public static void StartCharacterStatsTransExcel(FlatBufferBuilder builder) { builder.StartTable(4); }
  public static void AddTransSupportStats(FlatBufferBuilder builder, FlatData.StatType transSupportStats) { builder.AddInt(0, (int)transSupportStats, 0); }
  public static void AddEchelonExtensionType(FlatBufferBuilder builder, FlatData.EchelonExtensionType echelonExtensionType) { builder.AddInt(1, (int)echelonExtensionType, 0); }
  public static void AddTransSupportStatsFactor(FlatBufferBuilder builder, int transSupportStatsFactor) { builder.AddInt(2, transSupportStatsFactor, 0); }
  public static void AddStatTransType(FlatBufferBuilder builder, FlatData.StatTransType statTransType) { builder.AddInt(3, (int)statTransType, 0); }
  public static Offset<FlatData.CharacterStatsTransExcel> EndCharacterStatsTransExcel(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<FlatData.CharacterStatsTransExcel>(o);
  }
}


static public class CharacterStatsTransExcelVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*TransSupportStats*/, 4 /*FlatData.StatType*/, 4, false)
      && verifier.VerifyField(tablePos, 6 /*EchelonExtensionType*/, 4 /*FlatData.EchelonExtensionType*/, 4, false)
      && verifier.VerifyField(tablePos, 8 /*TransSupportStatsFactor*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 10 /*StatTransType*/, 4 /*FlatData.StatTransType*/, 4, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
