// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace FlatData
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct CharacterDialogSubtitleExcel : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static CharacterDialogSubtitleExcel GetRootAsCharacterDialogSubtitleExcel(ByteBuffer _bb) { return GetRootAsCharacterDialogSubtitleExcel(_bb, new CharacterDialogSubtitleExcel()); }
  public static CharacterDialogSubtitleExcel GetRootAsCharacterDialogSubtitleExcel(ByteBuffer _bb, CharacterDialogSubtitleExcel obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public CharacterDialogSubtitleExcel __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string LocalizeCVGroup { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetLocalizeCVGroupBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetLocalizeCVGroupBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetLocalizeCVGroupArray() { return __p.__vector_as_array<byte>(4); }
  public long CharacterId { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public string TLMID { get { int o = __p.__offset(8); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetTLMIDBytes() { return __p.__vector_as_span<byte>(8, 1); }
#else
  public ArraySegment<byte>? GetTLMIDBytes() { return __p.__vector_as_arraysegment(8); }
#endif
  public byte[] GetTLMIDArray() { return __p.__vector_as_array<byte>(8); }
  public long Duration { get { int o = __p.__offset(10); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public long DurationKr { get { int o = __p.__offset(12); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public bool Separate { get { int o = __p.__offset(14); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }
  public string LocalizeKR { get { int o = __p.__offset(16); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetLocalizeKRBytes() { return __p.__vector_as_span<byte>(16, 1); }
#else
  public ArraySegment<byte>? GetLocalizeKRBytes() { return __p.__vector_as_arraysegment(16); }
#endif
  public byte[] GetLocalizeKRArray() { return __p.__vector_as_array<byte>(16); }
  public string LocalizeJP { get { int o = __p.__offset(18); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetLocalizeJPBytes() { return __p.__vector_as_span<byte>(18, 1); }
#else
  public ArraySegment<byte>? GetLocalizeJPBytes() { return __p.__vector_as_arraysegment(18); }
#endif
  public byte[] GetLocalizeJPArray() { return __p.__vector_as_array<byte>(18); }
  public string LocalizeTH { get { int o = __p.__offset(20); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetLocalizeTHBytes() { return __p.__vector_as_span<byte>(20, 1); }
#else
  public ArraySegment<byte>? GetLocalizeTHBytes() { return __p.__vector_as_arraysegment(20); }
#endif
  public byte[] GetLocalizeTHArray() { return __p.__vector_as_array<byte>(20); }
  public string LocalizeTW { get { int o = __p.__offset(22); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetLocalizeTWBytes() { return __p.__vector_as_span<byte>(22, 1); }
#else
  public ArraySegment<byte>? GetLocalizeTWBytes() { return __p.__vector_as_arraysegment(22); }
#endif
  public byte[] GetLocalizeTWArray() { return __p.__vector_as_array<byte>(22); }
  public string LocalizeEN { get { int o = __p.__offset(24); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetLocalizeENBytes() { return __p.__vector_as_span<byte>(24, 1); }
#else
  public ArraySegment<byte>? GetLocalizeENBytes() { return __p.__vector_as_arraysegment(24); }
#endif
  public byte[] GetLocalizeENArray() { return __p.__vector_as_array<byte>(24); }

  public static Offset<FlatData.CharacterDialogSubtitleExcel> CreateCharacterDialogSubtitleExcel(FlatBufferBuilder builder,
      StringOffset LocalizeCVGroupOffset = default(StringOffset),
      long CharacterId = 0,
      StringOffset TLMIDOffset = default(StringOffset),
      long Duration = 0,
      long DurationKr = 0,
      bool Separate = false,
      StringOffset LocalizeKROffset = default(StringOffset),
      StringOffset LocalizeJPOffset = default(StringOffset),
      StringOffset LocalizeTHOffset = default(StringOffset),
      StringOffset LocalizeTWOffset = default(StringOffset),
      StringOffset LocalizeENOffset = default(StringOffset)) {
    builder.StartTable(11);
    CharacterDialogSubtitleExcel.AddDurationKr(builder, DurationKr);
    CharacterDialogSubtitleExcel.AddDuration(builder, Duration);
    CharacterDialogSubtitleExcel.AddCharacterId(builder, CharacterId);
    CharacterDialogSubtitleExcel.AddLocalizeEN(builder, LocalizeENOffset);
    CharacterDialogSubtitleExcel.AddLocalizeTW(builder, LocalizeTWOffset);
    CharacterDialogSubtitleExcel.AddLocalizeTH(builder, LocalizeTHOffset);
    CharacterDialogSubtitleExcel.AddLocalizeJP(builder, LocalizeJPOffset);
    CharacterDialogSubtitleExcel.AddLocalizeKR(builder, LocalizeKROffset);
    CharacterDialogSubtitleExcel.AddTLMID(builder, TLMIDOffset);
    CharacterDialogSubtitleExcel.AddLocalizeCVGroup(builder, LocalizeCVGroupOffset);
    CharacterDialogSubtitleExcel.AddSeparate(builder, Separate);
    return CharacterDialogSubtitleExcel.EndCharacterDialogSubtitleExcel(builder);
  }

  public static void StartCharacterDialogSubtitleExcel(FlatBufferBuilder builder) { builder.StartTable(11); }
  public static void AddLocalizeCVGroup(FlatBufferBuilder builder, StringOffset localizeCVGroupOffset) { builder.AddOffset(0, localizeCVGroupOffset.Value, 0); }
  public static void AddCharacterId(FlatBufferBuilder builder, long characterId) { builder.AddLong(1, characterId, 0); }
  public static void AddTLMID(FlatBufferBuilder builder, StringOffset tLMIDOffset) { builder.AddOffset(2, tLMIDOffset.Value, 0); }
  public static void AddDuration(FlatBufferBuilder builder, long duration) { builder.AddLong(3, duration, 0); }
  public static void AddDurationKr(FlatBufferBuilder builder, long durationKr) { builder.AddLong(4, durationKr, 0); }
  public static void AddSeparate(FlatBufferBuilder builder, bool separate) { builder.AddBool(5, separate, false); }
  public static void AddLocalizeKR(FlatBufferBuilder builder, StringOffset localizeKROffset) { builder.AddOffset(6, localizeKROffset.Value, 0); }
  public static void AddLocalizeJP(FlatBufferBuilder builder, StringOffset localizeJPOffset) { builder.AddOffset(7, localizeJPOffset.Value, 0); }
  public static void AddLocalizeTH(FlatBufferBuilder builder, StringOffset localizeTHOffset) { builder.AddOffset(8, localizeTHOffset.Value, 0); }
  public static void AddLocalizeTW(FlatBufferBuilder builder, StringOffset localizeTWOffset) { builder.AddOffset(9, localizeTWOffset.Value, 0); }
  public static void AddLocalizeEN(FlatBufferBuilder builder, StringOffset localizeENOffset) { builder.AddOffset(10, localizeENOffset.Value, 0); }
  public static Offset<FlatData.CharacterDialogSubtitleExcel> EndCharacterDialogSubtitleExcel(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<FlatData.CharacterDialogSubtitleExcel>(o);
  }
}


static public class CharacterDialogSubtitleExcelVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyString(tablePos, 4 /*LocalizeCVGroup*/, false)
      && verifier.VerifyField(tablePos, 6 /*CharacterId*/, 8 /*long*/, 8, false)
      && verifier.VerifyString(tablePos, 8 /*TLMID*/, false)
      && verifier.VerifyField(tablePos, 10 /*Duration*/, 8 /*long*/, 8, false)
      && verifier.VerifyField(tablePos, 12 /*DurationKr*/, 8 /*long*/, 8, false)
      && verifier.VerifyField(tablePos, 14 /*Separate*/, 1 /*bool*/, 1, false)
      && verifier.VerifyString(tablePos, 16 /*LocalizeKR*/, false)
      && verifier.VerifyString(tablePos, 18 /*LocalizeJP*/, false)
      && verifier.VerifyString(tablePos, 20 /*LocalizeTH*/, false)
      && verifier.VerifyString(tablePos, 22 /*LocalizeTW*/, false)
      && verifier.VerifyString(tablePos, 24 /*LocalizeEN*/, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
