// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace FlatData
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct CharacterDialogExcel : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static CharacterDialogExcel GetRootAsCharacterDialogExcel(ByteBuffer _bb) { return GetRootAsCharacterDialogExcel(_bb, new CharacterDialogExcel()); }
  public static CharacterDialogExcel GetRootAsCharacterDialogExcel(ByteBuffer _bb, CharacterDialogExcel obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public CharacterDialogExcel __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long CharacterId { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public long CostumeUniqueId { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public long DisplayOrder { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public FlatData.ProductionStep ProductionStep { get { int o = __p.__offset(10); return o != 0 ? (FlatData.ProductionStep)__p.bb.GetInt(o + __p.bb_pos) : FlatData.ProductionStep.ToDo; } }
  public FlatData.DialogCategory DialogCategory { get { int o = __p.__offset(12); return o != 0 ? (FlatData.DialogCategory)__p.bb.GetInt(o + __p.bb_pos) : FlatData.DialogCategory.Cafe; } }
  public FlatData.DialogCondition DialogCondition { get { int o = __p.__offset(14); return o != 0 ? (FlatData.DialogCondition)__p.bb.GetInt(o + __p.bb_pos) : FlatData.DialogCondition.Idle; } }
  public FlatData.Anniversary Anniversary { get { int o = __p.__offset(16); return o != 0 ? (FlatData.Anniversary)__p.bb.GetInt(o + __p.bb_pos) : FlatData.Anniversary.None; } }
  public string StartDate { get { int o = __p.__offset(18); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetStartDateBytes() { return __p.__vector_as_span<byte>(18, 1); }
#else
  public ArraySegment<byte>? GetStartDateBytes() { return __p.__vector_as_arraysegment(18); }
#endif
  public byte[] GetStartDateArray() { return __p.__vector_as_array<byte>(18); }
  public string EndDate { get { int o = __p.__offset(20); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetEndDateBytes() { return __p.__vector_as_span<byte>(20, 1); }
#else
  public ArraySegment<byte>? GetEndDateBytes() { return __p.__vector_as_arraysegment(20); }
#endif
  public byte[] GetEndDateArray() { return __p.__vector_as_array<byte>(20); }
  public long GroupId { get { int o = __p.__offset(22); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public FlatData.DialogType DialogType { get { int o = __p.__offset(24); return o != 0 ? (FlatData.DialogType)__p.bb.GetInt(o + __p.bb_pos) : FlatData.DialogType.Talk; } }
  public string ActionName { get { int o = __p.__offset(26); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetActionNameBytes() { return __p.__vector_as_span<byte>(26, 1); }
#else
  public ArraySegment<byte>? GetActionNameBytes() { return __p.__vector_as_arraysegment(26); }
#endif
  public byte[] GetActionNameArray() { return __p.__vector_as_array<byte>(26); }
  public long Duration { get { int o = __p.__offset(28); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public long DurationKr { get { int o = __p.__offset(30); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public string AnimationName { get { int o = __p.__offset(32); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetAnimationNameBytes() { return __p.__vector_as_span<byte>(32, 1); }
#else
  public ArraySegment<byte>? GetAnimationNameBytes() { return __p.__vector_as_arraysegment(32); }
#endif
  public byte[] GetAnimationNameArray() { return __p.__vector_as_array<byte>(32); }
  public string LocalizeKR { get { int o = __p.__offset(34); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetLocalizeKRBytes() { return __p.__vector_as_span<byte>(34, 1); }
#else
  public ArraySegment<byte>? GetLocalizeKRBytes() { return __p.__vector_as_arraysegment(34); }
#endif
  public byte[] GetLocalizeKRArray() { return __p.__vector_as_array<byte>(34); }
  public string LocalizeJP { get { int o = __p.__offset(36); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetLocalizeJPBytes() { return __p.__vector_as_span<byte>(36, 1); }
#else
  public ArraySegment<byte>? GetLocalizeJPBytes() { return __p.__vector_as_arraysegment(36); }
#endif
  public byte[] GetLocalizeJPArray() { return __p.__vector_as_array<byte>(36); }
  public string LocalizeTH { get { int o = __p.__offset(38); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetLocalizeTHBytes() { return __p.__vector_as_span<byte>(38, 1); }
#else
  public ArraySegment<byte>? GetLocalizeTHBytes() { return __p.__vector_as_arraysegment(38); }
#endif
  public byte[] GetLocalizeTHArray() { return __p.__vector_as_array<byte>(38); }
  public string LocalizeTW { get { int o = __p.__offset(40); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetLocalizeTWBytes() { return __p.__vector_as_span<byte>(40, 1); }
#else
  public ArraySegment<byte>? GetLocalizeTWBytes() { return __p.__vector_as_arraysegment(40); }
#endif
  public byte[] GetLocalizeTWArray() { return __p.__vector_as_array<byte>(40); }
  public string LocalizeEN { get { int o = __p.__offset(42); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetLocalizeENBytes() { return __p.__vector_as_span<byte>(42, 1); }
#else
  public ArraySegment<byte>? GetLocalizeENBytes() { return __p.__vector_as_arraysegment(42); }
#endif
  public byte[] GetLocalizeENArray() { return __p.__vector_as_array<byte>(42); }
  public uint VoiceId(int j) { int o = __p.__offset(44); return o != 0 ? __p.bb.GetUint(__p.__vector(o) + j * 4) : (uint)0; }
  public int VoiceIdLength { get { int o = __p.__offset(44); return o != 0 ? __p.__vector_len(o) : 0; } }
#if ENABLE_SPAN_T
  public Span<uint> GetVoiceIdBytes() { return __p.__vector_as_span<uint>(44, 4); }
#else
  public ArraySegment<byte>? GetVoiceIdBytes() { return __p.__vector_as_arraysegment(44); }
#endif
  public uint[] GetVoiceIdArray() { return __p.__vector_as_array<uint>(44); }
  public bool ApplyPosition { get { int o = __p.__offset(46); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }
  public float PosX { get { int o = __p.__offset(48); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public float PosY { get { int o = __p.__offset(50); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public bool CollectionVisible { get { int o = __p.__offset(52); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }
  public FlatData.CVCollectionType CVCollectionType { get { int o = __p.__offset(54); return o != 0 ? (FlatData.CVCollectionType)__p.bb.GetInt(o + __p.bb_pos) : FlatData.CVCollectionType.CVNormal; } }
  public long UnlockFavorRank { get { int o = __p.__offset(56); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public bool UnlockEquipWeapon { get { int o = __p.__offset(58); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }
  public string LocalizeCVGroup { get { int o = __p.__offset(60); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetLocalizeCVGroupBytes() { return __p.__vector_as_span<byte>(60, 1); }
#else
  public ArraySegment<byte>? GetLocalizeCVGroupBytes() { return __p.__vector_as_arraysegment(60); }
#endif
  public byte[] GetLocalizeCVGroupArray() { return __p.__vector_as_array<byte>(60); }
  public bool TeenMode { get { int o = __p.__offset(62); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }

  public static Offset<FlatData.CharacterDialogExcel> CreateCharacterDialogExcel(FlatBufferBuilder builder,
      long CharacterId = 0,
      long CostumeUniqueId = 0,
      long DisplayOrder = 0,
      FlatData.ProductionStep ProductionStep = FlatData.ProductionStep.ToDo,
      FlatData.DialogCategory DialogCategory = FlatData.DialogCategory.Cafe,
      FlatData.DialogCondition DialogCondition = FlatData.DialogCondition.Idle,
      FlatData.Anniversary Anniversary = FlatData.Anniversary.None,
      StringOffset StartDateOffset = default(StringOffset),
      StringOffset EndDateOffset = default(StringOffset),
      long GroupId = 0,
      FlatData.DialogType DialogType = FlatData.DialogType.Talk,
      StringOffset ActionNameOffset = default(StringOffset),
      long Duration = 0,
      long DurationKr = 0,
      StringOffset AnimationNameOffset = default(StringOffset),
      StringOffset LocalizeKROffset = default(StringOffset),
      StringOffset LocalizeJPOffset = default(StringOffset),
      StringOffset LocalizeTHOffset = default(StringOffset),
      StringOffset LocalizeTWOffset = default(StringOffset),
      StringOffset LocalizeENOffset = default(StringOffset),
      VectorOffset VoiceIdOffset = default(VectorOffset),
      bool ApplyPosition = false,
      float PosX = 0.0f,
      float PosY = 0.0f,
      bool CollectionVisible = false,
      FlatData.CVCollectionType CVCollectionType = FlatData.CVCollectionType.CVNormal,
      long UnlockFavorRank = 0,
      bool UnlockEquipWeapon = false,
      StringOffset LocalizeCVGroupOffset = default(StringOffset),
      bool TeenMode = false) {
    builder.StartTable(30);
    CharacterDialogExcel.AddUnlockFavorRank(builder, UnlockFavorRank);
    CharacterDialogExcel.AddDurationKr(builder, DurationKr);
    CharacterDialogExcel.AddDuration(builder, Duration);
    CharacterDialogExcel.AddGroupId(builder, GroupId);
    CharacterDialogExcel.AddDisplayOrder(builder, DisplayOrder);
    CharacterDialogExcel.AddCostumeUniqueId(builder, CostumeUniqueId);
    CharacterDialogExcel.AddCharacterId(builder, CharacterId);
    CharacterDialogExcel.AddLocalizeCVGroup(builder, LocalizeCVGroupOffset);
    CharacterDialogExcel.AddCVCollectionType(builder, CVCollectionType);
    CharacterDialogExcel.AddPosY(builder, PosY);
    CharacterDialogExcel.AddPosX(builder, PosX);
    CharacterDialogExcel.AddVoiceId(builder, VoiceIdOffset);
    CharacterDialogExcel.AddLocalizeEN(builder, LocalizeENOffset);
    CharacterDialogExcel.AddLocalizeTW(builder, LocalizeTWOffset);
    CharacterDialogExcel.AddLocalizeTH(builder, LocalizeTHOffset);
    CharacterDialogExcel.AddLocalizeJP(builder, LocalizeJPOffset);
    CharacterDialogExcel.AddLocalizeKR(builder, LocalizeKROffset);
    CharacterDialogExcel.AddAnimationName(builder, AnimationNameOffset);
    CharacterDialogExcel.AddActionName(builder, ActionNameOffset);
    CharacterDialogExcel.AddDialogType(builder, DialogType);
    CharacterDialogExcel.AddEndDate(builder, EndDateOffset);
    CharacterDialogExcel.AddStartDate(builder, StartDateOffset);
    CharacterDialogExcel.AddAnniversary(builder, Anniversary);
    CharacterDialogExcel.AddDialogCondition(builder, DialogCondition);
    CharacterDialogExcel.AddDialogCategory(builder, DialogCategory);
    CharacterDialogExcel.AddProductionStep(builder, ProductionStep);
    CharacterDialogExcel.AddTeenMode(builder, TeenMode);
    CharacterDialogExcel.AddUnlockEquipWeapon(builder, UnlockEquipWeapon);
    CharacterDialogExcel.AddCollectionVisible(builder, CollectionVisible);
    CharacterDialogExcel.AddApplyPosition(builder, ApplyPosition);
    return CharacterDialogExcel.EndCharacterDialogExcel(builder);
  }

  public static void StartCharacterDialogExcel(FlatBufferBuilder builder) { builder.StartTable(30); }
  public static void AddCharacterId(FlatBufferBuilder builder, long characterId) { builder.AddLong(0, characterId, 0); }
  public static void AddCostumeUniqueId(FlatBufferBuilder builder, long costumeUniqueId) { builder.AddLong(1, costumeUniqueId, 0); }
  public static void AddDisplayOrder(FlatBufferBuilder builder, long displayOrder) { builder.AddLong(2, displayOrder, 0); }
  public static void AddProductionStep(FlatBufferBuilder builder, FlatData.ProductionStep productionStep) { builder.AddInt(3, (int)productionStep, 0); }
  public static void AddDialogCategory(FlatBufferBuilder builder, FlatData.DialogCategory dialogCategory) { builder.AddInt(4, (int)dialogCategory, 0); }
  public static void AddDialogCondition(FlatBufferBuilder builder, FlatData.DialogCondition dialogCondition) { builder.AddInt(5, (int)dialogCondition, 0); }
  public static void AddAnniversary(FlatBufferBuilder builder, FlatData.Anniversary anniversary) { builder.AddInt(6, (int)anniversary, 0); }
  public static void AddStartDate(FlatBufferBuilder builder, StringOffset startDateOffset) { builder.AddOffset(7, startDateOffset.Value, 0); }
  public static void AddEndDate(FlatBufferBuilder builder, StringOffset endDateOffset) { builder.AddOffset(8, endDateOffset.Value, 0); }
  public static void AddGroupId(FlatBufferBuilder builder, long groupId) { builder.AddLong(9, groupId, 0); }
  public static void AddDialogType(FlatBufferBuilder builder, FlatData.DialogType dialogType) { builder.AddInt(10, (int)dialogType, 0); }
  public static void AddActionName(FlatBufferBuilder builder, StringOffset actionNameOffset) { builder.AddOffset(11, actionNameOffset.Value, 0); }
  public static void AddDuration(FlatBufferBuilder builder, long duration) { builder.AddLong(12, duration, 0); }
  public static void AddDurationKr(FlatBufferBuilder builder, long durationKr) { builder.AddLong(13, durationKr, 0); }
  public static void AddAnimationName(FlatBufferBuilder builder, StringOffset animationNameOffset) { builder.AddOffset(14, animationNameOffset.Value, 0); }
  public static void AddLocalizeKR(FlatBufferBuilder builder, StringOffset localizeKROffset) { builder.AddOffset(15, localizeKROffset.Value, 0); }
  public static void AddLocalizeJP(FlatBufferBuilder builder, StringOffset localizeJPOffset) { builder.AddOffset(16, localizeJPOffset.Value, 0); }
  public static void AddLocalizeTH(FlatBufferBuilder builder, StringOffset localizeTHOffset) { builder.AddOffset(17, localizeTHOffset.Value, 0); }
  public static void AddLocalizeTW(FlatBufferBuilder builder, StringOffset localizeTWOffset) { builder.AddOffset(18, localizeTWOffset.Value, 0); }
  public static void AddLocalizeEN(FlatBufferBuilder builder, StringOffset localizeENOffset) { builder.AddOffset(19, localizeENOffset.Value, 0); }
  public static void AddVoiceId(FlatBufferBuilder builder, VectorOffset voiceIdOffset) { builder.AddOffset(20, voiceIdOffset.Value, 0); }
  public static VectorOffset CreateVoiceIdVector(FlatBufferBuilder builder, uint[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddUint(data[i]); return builder.EndVector(); }
  public static VectorOffset CreateVoiceIdVectorBlock(FlatBufferBuilder builder, uint[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateVoiceIdVectorBlock(FlatBufferBuilder builder, ArraySegment<uint> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateVoiceIdVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<uint>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartVoiceIdVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddApplyPosition(FlatBufferBuilder builder, bool applyPosition) { builder.AddBool(21, applyPosition, false); }
  public static void AddPosX(FlatBufferBuilder builder, float posX) { builder.AddFloat(22, posX, 0.0f); }
  public static void AddPosY(FlatBufferBuilder builder, float posY) { builder.AddFloat(23, posY, 0.0f); }
  public static void AddCollectionVisible(FlatBufferBuilder builder, bool collectionVisible) { builder.AddBool(24, collectionVisible, false); }
  public static void AddCVCollectionType(FlatBufferBuilder builder, FlatData.CVCollectionType cVCollectionType) { builder.AddInt(25, (int)cVCollectionType, 0); }
  public static void AddUnlockFavorRank(FlatBufferBuilder builder, long unlockFavorRank) { builder.AddLong(26, unlockFavorRank, 0); }
  public static void AddUnlockEquipWeapon(FlatBufferBuilder builder, bool unlockEquipWeapon) { builder.AddBool(27, unlockEquipWeapon, false); }
  public static void AddLocalizeCVGroup(FlatBufferBuilder builder, StringOffset localizeCVGroupOffset) { builder.AddOffset(28, localizeCVGroupOffset.Value, 0); }
  public static void AddTeenMode(FlatBufferBuilder builder, bool teenMode) { builder.AddBool(29, teenMode, false); }
  public static Offset<FlatData.CharacterDialogExcel> EndCharacterDialogExcel(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<FlatData.CharacterDialogExcel>(o);
  }
}


static public class CharacterDialogExcelVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*CharacterId*/, 8 /*long*/, 8, false)
      && verifier.VerifyField(tablePos, 6 /*CostumeUniqueId*/, 8 /*long*/, 8, false)
      && verifier.VerifyField(tablePos, 8 /*DisplayOrder*/, 8 /*long*/, 8, false)
      && verifier.VerifyField(tablePos, 10 /*ProductionStep*/, 4 /*FlatData.ProductionStep*/, 4, false)
      && verifier.VerifyField(tablePos, 12 /*DialogCategory*/, 4 /*FlatData.DialogCategory*/, 4, false)
      && verifier.VerifyField(tablePos, 14 /*DialogCondition*/, 4 /*FlatData.DialogCondition*/, 4, false)
      && verifier.VerifyField(tablePos, 16 /*Anniversary*/, 4 /*FlatData.Anniversary*/, 4, false)
      && verifier.VerifyString(tablePos, 18 /*StartDate*/, false)
      && verifier.VerifyString(tablePos, 20 /*EndDate*/, false)
      && verifier.VerifyField(tablePos, 22 /*GroupId*/, 8 /*long*/, 8, false)
      && verifier.VerifyField(tablePos, 24 /*DialogType*/, 4 /*FlatData.DialogType*/, 4, false)
      && verifier.VerifyString(tablePos, 26 /*ActionName*/, false)
      && verifier.VerifyField(tablePos, 28 /*Duration*/, 8 /*long*/, 8, false)
      && verifier.VerifyField(tablePos, 30 /*DurationKr*/, 8 /*long*/, 8, false)
      && verifier.VerifyString(tablePos, 32 /*AnimationName*/, false)
      && verifier.VerifyString(tablePos, 34 /*LocalizeKR*/, false)
      && verifier.VerifyString(tablePos, 36 /*LocalizeJP*/, false)
      && verifier.VerifyString(tablePos, 38 /*LocalizeTH*/, false)
      && verifier.VerifyString(tablePos, 40 /*LocalizeTW*/, false)
      && verifier.VerifyString(tablePos, 42 /*LocalizeEN*/, false)
      && verifier.VerifyVectorOfData(tablePos, 44 /*VoiceId*/, 4 /*uint*/, false)
      && verifier.VerifyField(tablePos, 46 /*ApplyPosition*/, 1 /*bool*/, 1, false)
      && verifier.VerifyField(tablePos, 48 /*PosX*/, 4 /*float*/, 4, false)
      && verifier.VerifyField(tablePos, 50 /*PosY*/, 4 /*float*/, 4, false)
      && verifier.VerifyField(tablePos, 52 /*CollectionVisible*/, 1 /*bool*/, 1, false)
      && verifier.VerifyField(tablePos, 54 /*CVCollectionType*/, 4 /*FlatData.CVCollectionType*/, 4, false)
      && verifier.VerifyField(tablePos, 56 /*UnlockFavorRank*/, 8 /*long*/, 8, false)
      && verifier.VerifyField(tablePos, 58 /*UnlockEquipWeapon*/, 1 /*bool*/, 1, false)
      && verifier.VerifyString(tablePos, 60 /*LocalizeCVGroup*/, false)
      && verifier.VerifyField(tablePos, 62 /*TeenMode*/, 1 /*bool*/, 1, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
