// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace FlatData
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct CharacterVictoryInteractionExcel : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static CharacterVictoryInteractionExcel GetRootAsCharacterVictoryInteractionExcel(ByteBuffer _bb) { return GetRootAsCharacterVictoryInteractionExcel(_bb, new CharacterVictoryInteractionExcel()); }
  public static CharacterVictoryInteractionExcel GetRootAsCharacterVictoryInteractionExcel(ByteBuffer _bb, CharacterVictoryInteractionExcel obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public CharacterVictoryInteractionExcel __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long InteractionId { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public long CostumeId01 { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public int PositionIndex01 { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public string VictoryStartAnimationPath01 { get { int o = __p.__offset(10); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetVictoryStartAnimationPath01Bytes() { return __p.__vector_as_span<byte>(10, 1); }
#else
  public ArraySegment<byte>? GetVictoryStartAnimationPath01Bytes() { return __p.__vector_as_arraysegment(10); }
#endif
  public byte[] GetVictoryStartAnimationPath01Array() { return __p.__vector_as_array<byte>(10); }
  public string VictoryEndAnimationPath01 { get { int o = __p.__offset(12); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetVictoryEndAnimationPath01Bytes() { return __p.__vector_as_span<byte>(12, 1); }
#else
  public ArraySegment<byte>? GetVictoryEndAnimationPath01Bytes() { return __p.__vector_as_arraysegment(12); }
#endif
  public byte[] GetVictoryEndAnimationPath01Array() { return __p.__vector_as_array<byte>(12); }
  public FlatData.VoiceEvent VoiceEvent01 { get { int o = __p.__offset(14); return o != 0 ? (FlatData.VoiceEvent)__p.bb.GetInt(o + __p.bb_pos) : FlatData.VoiceEvent.OnTSA; } }
  public long CostumeId02 { get { int o = __p.__offset(16); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public int PositionIndex02 { get { int o = __p.__offset(18); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public string VictoryStartAnimationPath02 { get { int o = __p.__offset(20); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetVictoryStartAnimationPath02Bytes() { return __p.__vector_as_span<byte>(20, 1); }
#else
  public ArraySegment<byte>? GetVictoryStartAnimationPath02Bytes() { return __p.__vector_as_arraysegment(20); }
#endif
  public byte[] GetVictoryStartAnimationPath02Array() { return __p.__vector_as_array<byte>(20); }
  public string VictoryEndAnimationPath02 { get { int o = __p.__offset(22); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetVictoryEndAnimationPath02Bytes() { return __p.__vector_as_span<byte>(22, 1); }
#else
  public ArraySegment<byte>? GetVictoryEndAnimationPath02Bytes() { return __p.__vector_as_arraysegment(22); }
#endif
  public byte[] GetVictoryEndAnimationPath02Array() { return __p.__vector_as_array<byte>(22); }
  public FlatData.VoiceEvent VoiceEvent02 { get { int o = __p.__offset(24); return o != 0 ? (FlatData.VoiceEvent)__p.bb.GetInt(o + __p.bb_pos) : FlatData.VoiceEvent.OnTSA; } }
  public long CostumeId03 { get { int o = __p.__offset(26); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public int PositionIndex03 { get { int o = __p.__offset(28); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public string VictoryStartAnimationPath03 { get { int o = __p.__offset(30); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetVictoryStartAnimationPath03Bytes() { return __p.__vector_as_span<byte>(30, 1); }
#else
  public ArraySegment<byte>? GetVictoryStartAnimationPath03Bytes() { return __p.__vector_as_arraysegment(30); }
#endif
  public byte[] GetVictoryStartAnimationPath03Array() { return __p.__vector_as_array<byte>(30); }
  public string VictoryEndAnimationPath03 { get { int o = __p.__offset(32); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetVictoryEndAnimationPath03Bytes() { return __p.__vector_as_span<byte>(32, 1); }
#else
  public ArraySegment<byte>? GetVictoryEndAnimationPath03Bytes() { return __p.__vector_as_arraysegment(32); }
#endif
  public byte[] GetVictoryEndAnimationPath03Array() { return __p.__vector_as_array<byte>(32); }
  public FlatData.VoiceEvent VoiceEvent03 { get { int o = __p.__offset(34); return o != 0 ? (FlatData.VoiceEvent)__p.bb.GetInt(o + __p.bb_pos) : FlatData.VoiceEvent.OnTSA; } }
  public long CostumeId04 { get { int o = __p.__offset(36); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public int PositionIndex04 { get { int o = __p.__offset(38); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public string VictoryStartAnimationPath04 { get { int o = __p.__offset(40); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetVictoryStartAnimationPath04Bytes() { return __p.__vector_as_span<byte>(40, 1); }
#else
  public ArraySegment<byte>? GetVictoryStartAnimationPath04Bytes() { return __p.__vector_as_arraysegment(40); }
#endif
  public byte[] GetVictoryStartAnimationPath04Array() { return __p.__vector_as_array<byte>(40); }
  public string VictoryEndAnimationPath04 { get { int o = __p.__offset(42); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetVictoryEndAnimationPath04Bytes() { return __p.__vector_as_span<byte>(42, 1); }
#else
  public ArraySegment<byte>? GetVictoryEndAnimationPath04Bytes() { return __p.__vector_as_arraysegment(42); }
#endif
  public byte[] GetVictoryEndAnimationPath04Array() { return __p.__vector_as_array<byte>(42); }
  public FlatData.VoiceEvent VoiceEvent04 { get { int o = __p.__offset(44); return o != 0 ? (FlatData.VoiceEvent)__p.bb.GetInt(o + __p.bb_pos) : FlatData.VoiceEvent.OnTSA; } }
  public long CostumeId05 { get { int o = __p.__offset(46); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public int PositionIndex05 { get { int o = __p.__offset(48); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public string VictoryStartAnimationPath05 { get { int o = __p.__offset(50); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetVictoryStartAnimationPath05Bytes() { return __p.__vector_as_span<byte>(50, 1); }
#else
  public ArraySegment<byte>? GetVictoryStartAnimationPath05Bytes() { return __p.__vector_as_arraysegment(50); }
#endif
  public byte[] GetVictoryStartAnimationPath05Array() { return __p.__vector_as_array<byte>(50); }
  public string VictoryEndAnimationPath05 { get { int o = __p.__offset(52); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetVictoryEndAnimationPath05Bytes() { return __p.__vector_as_span<byte>(52, 1); }
#else
  public ArraySegment<byte>? GetVictoryEndAnimationPath05Bytes() { return __p.__vector_as_arraysegment(52); }
#endif
  public byte[] GetVictoryEndAnimationPath05Array() { return __p.__vector_as_array<byte>(52); }
  public FlatData.VoiceEvent VoiceEvent05 { get { int o = __p.__offset(54); return o != 0 ? (FlatData.VoiceEvent)__p.bb.GetInt(o + __p.bb_pos) : FlatData.VoiceEvent.OnTSA; } }
  public long CostumeId06 { get { int o = __p.__offset(56); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public int PositionIndex06 { get { int o = __p.__offset(58); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public string VictoryStartAnimationPath06 { get { int o = __p.__offset(60); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetVictoryStartAnimationPath06Bytes() { return __p.__vector_as_span<byte>(60, 1); }
#else
  public ArraySegment<byte>? GetVictoryStartAnimationPath06Bytes() { return __p.__vector_as_arraysegment(60); }
#endif
  public byte[] GetVictoryStartAnimationPath06Array() { return __p.__vector_as_array<byte>(60); }
  public string VictoryEndAnimationPath06 { get { int o = __p.__offset(62); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetVictoryEndAnimationPath06Bytes() { return __p.__vector_as_span<byte>(62, 1); }
#else
  public ArraySegment<byte>? GetVictoryEndAnimationPath06Bytes() { return __p.__vector_as_arraysegment(62); }
#endif
  public byte[] GetVictoryEndAnimationPath06Array() { return __p.__vector_as_array<byte>(62); }
  public FlatData.VoiceEvent VoiceEvent06 { get { int o = __p.__offset(64); return o != 0 ? (FlatData.VoiceEvent)__p.bb.GetInt(o + __p.bb_pos) : FlatData.VoiceEvent.OnTSA; } }

  public static Offset<FlatData.CharacterVictoryInteractionExcel> CreateCharacterVictoryInteractionExcel(FlatBufferBuilder builder,
      long InteractionId = 0,
      long CostumeId01 = 0,
      int PositionIndex01 = 0,
      StringOffset VictoryStartAnimationPath01Offset = default(StringOffset),
      StringOffset VictoryEndAnimationPath01Offset = default(StringOffset),
      FlatData.VoiceEvent VoiceEvent01 = FlatData.VoiceEvent.OnTSA,
      long CostumeId02 = 0,
      int PositionIndex02 = 0,
      StringOffset VictoryStartAnimationPath02Offset = default(StringOffset),
      StringOffset VictoryEndAnimationPath02Offset = default(StringOffset),
      FlatData.VoiceEvent VoiceEvent02 = FlatData.VoiceEvent.OnTSA,
      long CostumeId03 = 0,
      int PositionIndex03 = 0,
      StringOffset VictoryStartAnimationPath03Offset = default(StringOffset),
      StringOffset VictoryEndAnimationPath03Offset = default(StringOffset),
      FlatData.VoiceEvent VoiceEvent03 = FlatData.VoiceEvent.OnTSA,
      long CostumeId04 = 0,
      int PositionIndex04 = 0,
      StringOffset VictoryStartAnimationPath04Offset = default(StringOffset),
      StringOffset VictoryEndAnimationPath04Offset = default(StringOffset),
      FlatData.VoiceEvent VoiceEvent04 = FlatData.VoiceEvent.OnTSA,
      long CostumeId05 = 0,
      int PositionIndex05 = 0,
      StringOffset VictoryStartAnimationPath05Offset = default(StringOffset),
      StringOffset VictoryEndAnimationPath05Offset = default(StringOffset),
      FlatData.VoiceEvent VoiceEvent05 = FlatData.VoiceEvent.OnTSA,
      long CostumeId06 = 0,
      int PositionIndex06 = 0,
      StringOffset VictoryStartAnimationPath06Offset = default(StringOffset),
      StringOffset VictoryEndAnimationPath06Offset = default(StringOffset),
      FlatData.VoiceEvent VoiceEvent06 = FlatData.VoiceEvent.OnTSA) {
    builder.StartTable(31);
    CharacterVictoryInteractionExcel.AddCostumeId06(builder, CostumeId06);
    CharacterVictoryInteractionExcel.AddCostumeId05(builder, CostumeId05);
    CharacterVictoryInteractionExcel.AddCostumeId04(builder, CostumeId04);
    CharacterVictoryInteractionExcel.AddCostumeId03(builder, CostumeId03);
    CharacterVictoryInteractionExcel.AddCostumeId02(builder, CostumeId02);
    CharacterVictoryInteractionExcel.AddCostumeId01(builder, CostumeId01);
    CharacterVictoryInteractionExcel.AddInteractionId(builder, InteractionId);
    CharacterVictoryInteractionExcel.AddVoiceEvent06(builder, VoiceEvent06);
    CharacterVictoryInteractionExcel.AddVictoryEndAnimationPath06(builder, VictoryEndAnimationPath06Offset);
    CharacterVictoryInteractionExcel.AddVictoryStartAnimationPath06(builder, VictoryStartAnimationPath06Offset);
    CharacterVictoryInteractionExcel.AddPositionIndex06(builder, PositionIndex06);
    CharacterVictoryInteractionExcel.AddVoiceEvent05(builder, VoiceEvent05);
    CharacterVictoryInteractionExcel.AddVictoryEndAnimationPath05(builder, VictoryEndAnimationPath05Offset);
    CharacterVictoryInteractionExcel.AddVictoryStartAnimationPath05(builder, VictoryStartAnimationPath05Offset);
    CharacterVictoryInteractionExcel.AddPositionIndex05(builder, PositionIndex05);
    CharacterVictoryInteractionExcel.AddVoiceEvent04(builder, VoiceEvent04);
    CharacterVictoryInteractionExcel.AddVictoryEndAnimationPath04(builder, VictoryEndAnimationPath04Offset);
    CharacterVictoryInteractionExcel.AddVictoryStartAnimationPath04(builder, VictoryStartAnimationPath04Offset);
    CharacterVictoryInteractionExcel.AddPositionIndex04(builder, PositionIndex04);
    CharacterVictoryInteractionExcel.AddVoiceEvent03(builder, VoiceEvent03);
    CharacterVictoryInteractionExcel.AddVictoryEndAnimationPath03(builder, VictoryEndAnimationPath03Offset);
    CharacterVictoryInteractionExcel.AddVictoryStartAnimationPath03(builder, VictoryStartAnimationPath03Offset);
    CharacterVictoryInteractionExcel.AddPositionIndex03(builder, PositionIndex03);
    CharacterVictoryInteractionExcel.AddVoiceEvent02(builder, VoiceEvent02);
    CharacterVictoryInteractionExcel.AddVictoryEndAnimationPath02(builder, VictoryEndAnimationPath02Offset);
    CharacterVictoryInteractionExcel.AddVictoryStartAnimationPath02(builder, VictoryStartAnimationPath02Offset);
    CharacterVictoryInteractionExcel.AddPositionIndex02(builder, PositionIndex02);
    CharacterVictoryInteractionExcel.AddVoiceEvent01(builder, VoiceEvent01);
    CharacterVictoryInteractionExcel.AddVictoryEndAnimationPath01(builder, VictoryEndAnimationPath01Offset);
    CharacterVictoryInteractionExcel.AddVictoryStartAnimationPath01(builder, VictoryStartAnimationPath01Offset);
    CharacterVictoryInteractionExcel.AddPositionIndex01(builder, PositionIndex01);
    return CharacterVictoryInteractionExcel.EndCharacterVictoryInteractionExcel(builder);
  }

  public static void StartCharacterVictoryInteractionExcel(FlatBufferBuilder builder) { builder.StartTable(31); }
  public static void AddInteractionId(FlatBufferBuilder builder, long interactionId) { builder.AddLong(0, interactionId, 0); }
  public static void AddCostumeId01(FlatBufferBuilder builder, long costumeId01) { builder.AddLong(1, costumeId01, 0); }
  public static void AddPositionIndex01(FlatBufferBuilder builder, int positionIndex01) { builder.AddInt(2, positionIndex01, 0); }
  public static void AddVictoryStartAnimationPath01(FlatBufferBuilder builder, StringOffset victoryStartAnimationPath01Offset) { builder.AddOffset(3, victoryStartAnimationPath01Offset.Value, 0); }
  public static void AddVictoryEndAnimationPath01(FlatBufferBuilder builder, StringOffset victoryEndAnimationPath01Offset) { builder.AddOffset(4, victoryEndAnimationPath01Offset.Value, 0); }
  public static void AddVoiceEvent01(FlatBufferBuilder builder, FlatData.VoiceEvent voiceEvent01) { builder.AddInt(5, (int)voiceEvent01, 0); }
  public static void AddCostumeId02(FlatBufferBuilder builder, long costumeId02) { builder.AddLong(6, costumeId02, 0); }
  public static void AddPositionIndex02(FlatBufferBuilder builder, int positionIndex02) { builder.AddInt(7, positionIndex02, 0); }
  public static void AddVictoryStartAnimationPath02(FlatBufferBuilder builder, StringOffset victoryStartAnimationPath02Offset) { builder.AddOffset(8, victoryStartAnimationPath02Offset.Value, 0); }
  public static void AddVictoryEndAnimationPath02(FlatBufferBuilder builder, StringOffset victoryEndAnimationPath02Offset) { builder.AddOffset(9, victoryEndAnimationPath02Offset.Value, 0); }
  public static void AddVoiceEvent02(FlatBufferBuilder builder, FlatData.VoiceEvent voiceEvent02) { builder.AddInt(10, (int)voiceEvent02, 0); }
  public static void AddCostumeId03(FlatBufferBuilder builder, long costumeId03) { builder.AddLong(11, costumeId03, 0); }
  public static void AddPositionIndex03(FlatBufferBuilder builder, int positionIndex03) { builder.AddInt(12, positionIndex03, 0); }
  public static void AddVictoryStartAnimationPath03(FlatBufferBuilder builder, StringOffset victoryStartAnimationPath03Offset) { builder.AddOffset(13, victoryStartAnimationPath03Offset.Value, 0); }
  public static void AddVictoryEndAnimationPath03(FlatBufferBuilder builder, StringOffset victoryEndAnimationPath03Offset) { builder.AddOffset(14, victoryEndAnimationPath03Offset.Value, 0); }
  public static void AddVoiceEvent03(FlatBufferBuilder builder, FlatData.VoiceEvent voiceEvent03) { builder.AddInt(15, (int)voiceEvent03, 0); }
  public static void AddCostumeId04(FlatBufferBuilder builder, long costumeId04) { builder.AddLong(16, costumeId04, 0); }
  public static void AddPositionIndex04(FlatBufferBuilder builder, int positionIndex04) { builder.AddInt(17, positionIndex04, 0); }
  public static void AddVictoryStartAnimationPath04(FlatBufferBuilder builder, StringOffset victoryStartAnimationPath04Offset) { builder.AddOffset(18, victoryStartAnimationPath04Offset.Value, 0); }
  public static void AddVictoryEndAnimationPath04(FlatBufferBuilder builder, StringOffset victoryEndAnimationPath04Offset) { builder.AddOffset(19, victoryEndAnimationPath04Offset.Value, 0); }
  public static void AddVoiceEvent04(FlatBufferBuilder builder, FlatData.VoiceEvent voiceEvent04) { builder.AddInt(20, (int)voiceEvent04, 0); }
  public static void AddCostumeId05(FlatBufferBuilder builder, long costumeId05) { builder.AddLong(21, costumeId05, 0); }
  public static void AddPositionIndex05(FlatBufferBuilder builder, int positionIndex05) { builder.AddInt(22, positionIndex05, 0); }
  public static void AddVictoryStartAnimationPath05(FlatBufferBuilder builder, StringOffset victoryStartAnimationPath05Offset) { builder.AddOffset(23, victoryStartAnimationPath05Offset.Value, 0); }
  public static void AddVictoryEndAnimationPath05(FlatBufferBuilder builder, StringOffset victoryEndAnimationPath05Offset) { builder.AddOffset(24, victoryEndAnimationPath05Offset.Value, 0); }
  public static void AddVoiceEvent05(FlatBufferBuilder builder, FlatData.VoiceEvent voiceEvent05) { builder.AddInt(25, (int)voiceEvent05, 0); }
  public static void AddCostumeId06(FlatBufferBuilder builder, long costumeId06) { builder.AddLong(26, costumeId06, 0); }
  public static void AddPositionIndex06(FlatBufferBuilder builder, int positionIndex06) { builder.AddInt(27, positionIndex06, 0); }
  public static void AddVictoryStartAnimationPath06(FlatBufferBuilder builder, StringOffset victoryStartAnimationPath06Offset) { builder.AddOffset(28, victoryStartAnimationPath06Offset.Value, 0); }
  public static void AddVictoryEndAnimationPath06(FlatBufferBuilder builder, StringOffset victoryEndAnimationPath06Offset) { builder.AddOffset(29, victoryEndAnimationPath06Offset.Value, 0); }
  public static void AddVoiceEvent06(FlatBufferBuilder builder, FlatData.VoiceEvent voiceEvent06) { builder.AddInt(30, (int)voiceEvent06, 0); }
  public static Offset<FlatData.CharacterVictoryInteractionExcel> EndCharacterVictoryInteractionExcel(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<FlatData.CharacterVictoryInteractionExcel>(o);
  }
}


static public class CharacterVictoryInteractionExcelVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*InteractionId*/, 8 /*long*/, 8, false)
      && verifier.VerifyField(tablePos, 6 /*CostumeId01*/, 8 /*long*/, 8, false)
      && verifier.VerifyField(tablePos, 8 /*PositionIndex01*/, 4 /*int*/, 4, false)
      && verifier.VerifyString(tablePos, 10 /*VictoryStartAnimationPath01*/, false)
      && verifier.VerifyString(tablePos, 12 /*VictoryEndAnimationPath01*/, false)
      && verifier.VerifyField(tablePos, 14 /*VoiceEvent01*/, 4 /*FlatData.VoiceEvent*/, 4, false)
      && verifier.VerifyField(tablePos, 16 /*CostumeId02*/, 8 /*long*/, 8, false)
      && verifier.VerifyField(tablePos, 18 /*PositionIndex02*/, 4 /*int*/, 4, false)
      && verifier.VerifyString(tablePos, 20 /*VictoryStartAnimationPath02*/, false)
      && verifier.VerifyString(tablePos, 22 /*VictoryEndAnimationPath02*/, false)
      && verifier.VerifyField(tablePos, 24 /*VoiceEvent02*/, 4 /*FlatData.VoiceEvent*/, 4, false)
      && verifier.VerifyField(tablePos, 26 /*CostumeId03*/, 8 /*long*/, 8, false)
      && verifier.VerifyField(tablePos, 28 /*PositionIndex03*/, 4 /*int*/, 4, false)
      && verifier.VerifyString(tablePos, 30 /*VictoryStartAnimationPath03*/, false)
      && verifier.VerifyString(tablePos, 32 /*VictoryEndAnimationPath03*/, false)
      && verifier.VerifyField(tablePos, 34 /*VoiceEvent03*/, 4 /*FlatData.VoiceEvent*/, 4, false)
      && verifier.VerifyField(tablePos, 36 /*CostumeId04*/, 8 /*long*/, 8, false)
      && verifier.VerifyField(tablePos, 38 /*PositionIndex04*/, 4 /*int*/, 4, false)
      && verifier.VerifyString(tablePos, 40 /*VictoryStartAnimationPath04*/, false)
      && verifier.VerifyString(tablePos, 42 /*VictoryEndAnimationPath04*/, false)
      && verifier.VerifyField(tablePos, 44 /*VoiceEvent04*/, 4 /*FlatData.VoiceEvent*/, 4, false)
      && verifier.VerifyField(tablePos, 46 /*CostumeId05*/, 8 /*long*/, 8, false)
      && verifier.VerifyField(tablePos, 48 /*PositionIndex05*/, 4 /*int*/, 4, false)
      && verifier.VerifyString(tablePos, 50 /*VictoryStartAnimationPath05*/, false)
      && verifier.VerifyString(tablePos, 52 /*VictoryEndAnimationPath05*/, false)
      && verifier.VerifyField(tablePos, 54 /*VoiceEvent05*/, 4 /*FlatData.VoiceEvent*/, 4, false)
      && verifier.VerifyField(tablePos, 56 /*CostumeId06*/, 8 /*long*/, 8, false)
      && verifier.VerifyField(tablePos, 58 /*PositionIndex06*/, 4 /*int*/, 4, false)
      && verifier.VerifyString(tablePos, 60 /*VictoryStartAnimationPath06*/, false)
      && verifier.VerifyString(tablePos, 62 /*VictoryEndAnimationPath06*/, false)
      && verifier.VerifyField(tablePos, 64 /*VoiceEvent06*/, 4 /*FlatData.VoiceEvent*/, 4, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
