// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace FlatData
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct ClanRewardExcel : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static ClanRewardExcel GetRootAsClanRewardExcel(ByteBuffer _bb) { return GetRootAsClanRewardExcel(_bb, new ClanRewardExcel()); }
  public static ClanRewardExcel GetRootAsClanRewardExcel(ByteBuffer _bb, ClanRewardExcel obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public ClanRewardExcel __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public FlatData.ClanRewardType ClanRewardType { get { int o = __p.__offset(4); return o != 0 ? (FlatData.ClanRewardType)__p.bb.GetInt(o + __p.bb_pos) : FlatData.ClanRewardType.None; } }
  public FlatData.EchelonType EchelonType { get { int o = __p.__offset(6); return o != 0 ? (FlatData.EchelonType)__p.bb.GetInt(o + __p.bb_pos) : FlatData.EchelonType.None; } }
  public FlatData.ParcelType RewardParcelType { get { int o = __p.__offset(8); return o != 0 ? (FlatData.ParcelType)__p.bb.GetInt(o + __p.bb_pos) : FlatData.ParcelType.None; } }
  public long RewardParcelId { get { int o = __p.__offset(10); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public long RewardParcelAmount { get { int o = __p.__offset(12); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }

  public static Offset<FlatData.ClanRewardExcel> CreateClanRewardExcel(FlatBufferBuilder builder,
      FlatData.ClanRewardType ClanRewardType = FlatData.ClanRewardType.None,
      FlatData.EchelonType EchelonType = FlatData.EchelonType.None,
      FlatData.ParcelType RewardParcelType = FlatData.ParcelType.None,
      long RewardParcelId = 0,
      long RewardParcelAmount = 0) {
    builder.StartTable(5);
    ClanRewardExcel.AddRewardParcelAmount(builder, RewardParcelAmount);
    ClanRewardExcel.AddRewardParcelId(builder, RewardParcelId);
    ClanRewardExcel.AddRewardParcelType(builder, RewardParcelType);
    ClanRewardExcel.AddEchelonType(builder, EchelonType);
    ClanRewardExcel.AddClanRewardType(builder, ClanRewardType);
    return ClanRewardExcel.EndClanRewardExcel(builder);
  }

  public static void StartClanRewardExcel(FlatBufferBuilder builder) { builder.StartTable(5); }
  public static void AddClanRewardType(FlatBufferBuilder builder, FlatData.ClanRewardType clanRewardType) { builder.AddInt(0, (int)clanRewardType, 0); }
  public static void AddEchelonType(FlatBufferBuilder builder, FlatData.EchelonType echelonType) { builder.AddInt(1, (int)echelonType, 0); }
  public static void AddRewardParcelType(FlatBufferBuilder builder, FlatData.ParcelType rewardParcelType) { builder.AddInt(2, (int)rewardParcelType, 0); }
  public static void AddRewardParcelId(FlatBufferBuilder builder, long rewardParcelId) { builder.AddLong(3, rewardParcelId, 0); }
  public static void AddRewardParcelAmount(FlatBufferBuilder builder, long rewardParcelAmount) { builder.AddLong(4, rewardParcelAmount, 0); }
  public static Offset<FlatData.ClanRewardExcel> EndClanRewardExcel(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<FlatData.ClanRewardExcel>(o);
  }
}


static public class ClanRewardExcelVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*ClanRewardType*/, 4 /*FlatData.ClanRewardType*/, 4, false)
      && verifier.VerifyField(tablePos, 6 /*EchelonType*/, 4 /*FlatData.EchelonType*/, 4, false)
      && verifier.VerifyField(tablePos, 8 /*RewardParcelType*/, 4 /*FlatData.ParcelType*/, 4, false)
      && verifier.VerifyField(tablePos, 10 /*RewardParcelId*/, 8 /*long*/, 8, false)
      && verifier.VerifyField(tablePos, 12 /*RewardParcelAmount*/, 8 /*long*/, 8, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
