// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace FlatData
{

public enum ConsumeCondition : int
{
  And = 0,
  Or = 1,
};


}
