// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace FlatData
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct ContentsFeverExcel : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static ContentsFeverExcel GetRootAsContentsFeverExcel(ByteBuffer _bb) { return GetRootAsContentsFeverExcel(_bb, new ContentsFeverExcel()); }
  public static ContentsFeverExcel GetRootAsContentsFeverExcel(ByteBuffer _bb, ContentsFeverExcel obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public ContentsFeverExcel __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public FlatData.FeverBattleType ConditionContent { get { int o = __p.__offset(4); return o != 0 ? (FlatData.FeverBattleType)__p.bb.GetInt(o + __p.bb_pos) : FlatData.FeverBattleType.Campaign; } }
  public FlatData.SkillPriorityCheckTarget SkillFeverCheckCondition { get { int o = __p.__offset(6); return o != 0 ? (FlatData.SkillPriorityCheckTarget)__p.bb.GetInt(o + __p.bb_pos) : FlatData.SkillPriorityCheckTarget.Ally; } }
  public long SkillCostFever { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public long FeverStartTime { get { int o = __p.__offset(10); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public long FeverDurationTime { get { int o = __p.__offset(12); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }

  public static Offset<FlatData.ContentsFeverExcel> CreateContentsFeverExcel(FlatBufferBuilder builder,
      FlatData.FeverBattleType ConditionContent = FlatData.FeverBattleType.Campaign,
      FlatData.SkillPriorityCheckTarget SkillFeverCheckCondition = FlatData.SkillPriorityCheckTarget.Ally,
      long SkillCostFever = 0,
      long FeverStartTime = 0,
      long FeverDurationTime = 0) {
    builder.StartTable(5);
    ContentsFeverExcel.AddFeverDurationTime(builder, FeverDurationTime);
    ContentsFeverExcel.AddFeverStartTime(builder, FeverStartTime);
    ContentsFeverExcel.AddSkillCostFever(builder, SkillCostFever);
    ContentsFeverExcel.AddSkillFeverCheckCondition(builder, SkillFeverCheckCondition);
    ContentsFeverExcel.AddConditionContent(builder, ConditionContent);
    return ContentsFeverExcel.EndContentsFeverExcel(builder);
  }

  public static void StartContentsFeverExcel(FlatBufferBuilder builder) { builder.StartTable(5); }
  public static void AddConditionContent(FlatBufferBuilder builder, FlatData.FeverBattleType conditionContent) { builder.AddInt(0, (int)conditionContent, 0); }
  public static void AddSkillFeverCheckCondition(FlatBufferBuilder builder, FlatData.SkillPriorityCheckTarget skillFeverCheckCondition) { builder.AddInt(1, (int)skillFeverCheckCondition, 0); }
  public static void AddSkillCostFever(FlatBufferBuilder builder, long skillCostFever) { builder.AddLong(2, skillCostFever, 0); }
  public static void AddFeverStartTime(FlatBufferBuilder builder, long feverStartTime) { builder.AddLong(3, feverStartTime, 0); }
  public static void AddFeverDurationTime(FlatBufferBuilder builder, long feverDurationTime) { builder.AddLong(4, feverDurationTime, 0); }
  public static Offset<FlatData.ContentsFeverExcel> EndContentsFeverExcel(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<FlatData.ContentsFeverExcel>(o);
  }
}


static public class ContentsFeverExcelVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*ConditionContent*/, 4 /*FlatData.FeverBattleType*/, 4, false)
      && verifier.VerifyField(tablePos, 6 /*SkillFeverCheckCondition*/, 4 /*FlatData.SkillPriorityCheckTarget*/, 4, false)
      && verifier.VerifyField(tablePos, 8 /*SkillCostFever*/, 8 /*long*/, 8, false)
      && verifier.VerifyField(tablePos, 10 /*FeverStartTime*/, 8 /*long*/, 8, false)
      && verifier.VerifyField(tablePos, 12 /*FeverDurationTime*/, 8 /*long*/, 8, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
