// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace FlatData
{

public enum EchelonExtensionType : int
{
  Base = 0,
  Extension = 1,
};


}
