// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace FlatData
{

public enum EmblemDisplayType : int
{
  Always = 0,
  Time = 1,
  Favor = 2,
  Potential = 3,
};


}
