// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace FlatData
{

public enum EventContentDiceRaceNodeType : int
{
  StartNode = 0,
  RewardNode = 1,
  MoveForwardNode = 2,
  SpecialRewardNode = 3,
};


}
