// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace FlatData
{

public enum EventContentItemType : int
{
  EventPoint = 0,
  EventToken1 = 1,
  EventToken2 = 2,
  EventToken3 = 3,
  EventToken4 = 4,
  EventToken5 = 5,
  EventMeetUpTicket = 6,
  EventEtcItem = 7,
};


}
