// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace FlatData
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct FieldDateExcel : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static FieldDateExcel GetRootAsFieldDateExcel(ByteBuffer _bb) { return GetRootAsFieldDateExcel(_bb, new FieldDateExcel()); }
  public static FieldDateExcel GetRootAsFieldDateExcel(ByteBuffer _bb, FieldDateExcel obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public FieldDateExcel __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long SeasonId { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public long UniqueId { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public long OpenDate { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public string DateLocalizeKey { get { int o = __p.__offset(10); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetDateLocalizeKeyBytes() { return __p.__vector_as_span<byte>(10, 1); }
#else
  public ArraySegment<byte>? GetDateLocalizeKeyBytes() { return __p.__vector_as_arraysegment(10); }
#endif
  public byte[] GetDateLocalizeKeyArray() { return __p.__vector_as_array<byte>(10); }
  public long EntrySceneId { get { int o = __p.__offset(12); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public FlatData.FieldConditionType StartConditionType { get { int o = __p.__offset(14); return o != 0 ? (FlatData.FieldConditionType)__p.bb.GetInt(o + __p.bb_pos) : FlatData.FieldConditionType.Invalid; } }
  public long StartConditionId { get { int o = __p.__offset(16); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public FlatData.FieldConditionType EndConditionType { get { int o = __p.__offset(18); return o != 0 ? (FlatData.FieldConditionType)__p.bb.GetInt(o + __p.bb_pos) : FlatData.FieldConditionType.Invalid; } }
  public long EndConditionId { get { int o = __p.__offset(20); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public FlatData.FieldConditionType EndReadyConditionType { get { int o = __p.__offset(22); return o != 0 ? (FlatData.FieldConditionType)__p.bb.GetInt(o + __p.bb_pos) : FlatData.FieldConditionType.Invalid; } }
  public long EndReadyConditionId { get { int o = __p.__offset(24); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public long OpenConditionStage { get { int o = __p.__offset(26); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public string CharacterIconPath { get { int o = __p.__offset(28); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetCharacterIconPathBytes() { return __p.__vector_as_span<byte>(28, 1); }
#else
  public ArraySegment<byte>? GetCharacterIconPathBytes() { return __p.__vector_as_arraysegment(28); }
#endif
  public byte[] GetCharacterIconPathArray() { return __p.__vector_as_array<byte>(28); }
  public string DateResultBGPath { get { int o = __p.__offset(30); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetDateResultBGPathBytes() { return __p.__vector_as_span<byte>(30, 1); }
#else
  public ArraySegment<byte>? GetDateResultBGPathBytes() { return __p.__vector_as_arraysegment(30); }
#endif
  public byte[] GetDateResultBGPathArray() { return __p.__vector_as_array<byte>(30); }
  public string DateResultSpinePath { get { int o = __p.__offset(32); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetDateResultSpinePathBytes() { return __p.__vector_as_span<byte>(32, 1); }
#else
  public ArraySegment<byte>? GetDateResultSpinePathBytes() { return __p.__vector_as_arraysegment(32); }
#endif
  public byte[] GetDateResultSpinePathArray() { return __p.__vector_as_array<byte>(32); }
  public float DateResultSpineOffsetX { get { int o = __p.__offset(34); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }

  public static Offset<FlatData.FieldDateExcel> CreateFieldDateExcel(FlatBufferBuilder builder,
      long SeasonId = 0,
      long UniqueId = 0,
      long OpenDate = 0,
      StringOffset DateLocalizeKeyOffset = default(StringOffset),
      long EntrySceneId = 0,
      FlatData.FieldConditionType StartConditionType = FlatData.FieldConditionType.Invalid,
      long StartConditionId = 0,
      FlatData.FieldConditionType EndConditionType = FlatData.FieldConditionType.Invalid,
      long EndConditionId = 0,
      FlatData.FieldConditionType EndReadyConditionType = FlatData.FieldConditionType.Invalid,
      long EndReadyConditionId = 0,
      long OpenConditionStage = 0,
      StringOffset CharacterIconPathOffset = default(StringOffset),
      StringOffset DateResultBGPathOffset = default(StringOffset),
      StringOffset DateResultSpinePathOffset = default(StringOffset),
      float DateResultSpineOffsetX = 0.0f) {
    builder.StartTable(16);
    FieldDateExcel.AddOpenConditionStage(builder, OpenConditionStage);
    FieldDateExcel.AddEndReadyConditionId(builder, EndReadyConditionId);
    FieldDateExcel.AddEndConditionId(builder, EndConditionId);
    FieldDateExcel.AddStartConditionId(builder, StartConditionId);
    FieldDateExcel.AddEntrySceneId(builder, EntrySceneId);
    FieldDateExcel.AddOpenDate(builder, OpenDate);
    FieldDateExcel.AddUniqueId(builder, UniqueId);
    FieldDateExcel.AddSeasonId(builder, SeasonId);
    FieldDateExcel.AddDateResultSpineOffsetX(builder, DateResultSpineOffsetX);
    FieldDateExcel.AddDateResultSpinePath(builder, DateResultSpinePathOffset);
    FieldDateExcel.AddDateResultBGPath(builder, DateResultBGPathOffset);
    FieldDateExcel.AddCharacterIconPath(builder, CharacterIconPathOffset);
    FieldDateExcel.AddEndReadyConditionType(builder, EndReadyConditionType);
    FieldDateExcel.AddEndConditionType(builder, EndConditionType);
    FieldDateExcel.AddStartConditionType(builder, StartConditionType);
    FieldDateExcel.AddDateLocalizeKey(builder, DateLocalizeKeyOffset);
    return FieldDateExcel.EndFieldDateExcel(builder);
  }

  public static void StartFieldDateExcel(FlatBufferBuilder builder) { builder.StartTable(16); }
  public static void AddSeasonId(FlatBufferBuilder builder, long seasonId) { builder.AddLong(0, seasonId, 0); }
  public static void AddUniqueId(FlatBufferBuilder builder, long uniqueId) { builder.AddLong(1, uniqueId, 0); }
  public static void AddOpenDate(FlatBufferBuilder builder, long openDate) { builder.AddLong(2, openDate, 0); }
  public static void AddDateLocalizeKey(FlatBufferBuilder builder, StringOffset dateLocalizeKeyOffset) { builder.AddOffset(3, dateLocalizeKeyOffset.Value, 0); }
  public static void AddEntrySceneId(FlatBufferBuilder builder, long entrySceneId) { builder.AddLong(4, entrySceneId, 0); }
  public static void AddStartConditionType(FlatBufferBuilder builder, FlatData.FieldConditionType startConditionType) { builder.AddInt(5, (int)startConditionType, 0); }
  public static void AddStartConditionId(FlatBufferBuilder builder, long startConditionId) { builder.AddLong(6, startConditionId, 0); }
  public static void AddEndConditionType(FlatBufferBuilder builder, FlatData.FieldConditionType endConditionType) { builder.AddInt(7, (int)endConditionType, 0); }
  public static void AddEndConditionId(FlatBufferBuilder builder, long endConditionId) { builder.AddLong(8, endConditionId, 0); }
  public static void AddEndReadyConditionType(FlatBufferBuilder builder, FlatData.FieldConditionType endReadyConditionType) { builder.AddInt(9, (int)endReadyConditionType, 0); }
  public static void AddEndReadyConditionId(FlatBufferBuilder builder, long endReadyConditionId) { builder.AddLong(10, endReadyConditionId, 0); }
  public static void AddOpenConditionStage(FlatBufferBuilder builder, long openConditionStage) { builder.AddLong(11, openConditionStage, 0); }
  public static void AddCharacterIconPath(FlatBufferBuilder builder, StringOffset characterIconPathOffset) { builder.AddOffset(12, characterIconPathOffset.Value, 0); }
  public static void AddDateResultBGPath(FlatBufferBuilder builder, StringOffset dateResultBGPathOffset) { builder.AddOffset(13, dateResultBGPathOffset.Value, 0); }
  public static void AddDateResultSpinePath(FlatBufferBuilder builder, StringOffset dateResultSpinePathOffset) { builder.AddOffset(14, dateResultSpinePathOffset.Value, 0); }
  public static void AddDateResultSpineOffsetX(FlatBufferBuilder builder, float dateResultSpineOffsetX) { builder.AddFloat(15, dateResultSpineOffsetX, 0.0f); }
  public static Offset<FlatData.FieldDateExcel> EndFieldDateExcel(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<FlatData.FieldDateExcel>(o);
  }
}


static public class FieldDateExcelVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*SeasonId*/, 8 /*long*/, 8, false)
      && verifier.VerifyField(tablePos, 6 /*UniqueId*/, 8 /*long*/, 8, false)
      && verifier.VerifyField(tablePos, 8 /*OpenDate*/, 8 /*long*/, 8, false)
      && verifier.VerifyString(tablePos, 10 /*DateLocalizeKey*/, false)
      && verifier.VerifyField(tablePos, 12 /*EntrySceneId*/, 8 /*long*/, 8, false)
      && verifier.VerifyField(tablePos, 14 /*StartConditionType*/, 4 /*FlatData.FieldConditionType*/, 4, false)
      && verifier.VerifyField(tablePos, 16 /*StartConditionId*/, 8 /*long*/, 8, false)
      && verifier.VerifyField(tablePos, 18 /*EndConditionType*/, 4 /*FlatData.FieldConditionType*/, 4, false)
      && verifier.VerifyField(tablePos, 20 /*EndConditionId*/, 8 /*long*/, 8, false)
      && verifier.VerifyField(tablePos, 22 /*EndReadyConditionType*/, 4 /*FlatData.FieldConditionType*/, 4, false)
      && verifier.VerifyField(tablePos, 24 /*EndReadyConditionId*/, 8 /*long*/, 8, false)
      && verifier.VerifyField(tablePos, 26 /*OpenConditionStage*/, 8 /*long*/, 8, false)
      && verifier.VerifyString(tablePos, 28 /*CharacterIconPath*/, false)
      && verifier.VerifyString(tablePos, 30 /*DateResultBGPath*/, false)
      && verifier.VerifyString(tablePos, 32 /*DateResultSpinePath*/, false)
      && verifier.VerifyField(tablePos, 34 /*DateResultSpineOffsetX*/, 4 /*float*/, 4, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
