// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace FlatData
{

public enum FieldConditionClass : int
{
  AndOr = 0,
  OrAnd = 1,
  Multi = 2,
};


}
