// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace FlatData
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct Form : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static Form GetRootAsForm(ByteBuffer _bb) { return GetRootAsForm(_bb, new Form()); }
  public static Form GetRootAsForm(ByteBuffer _bb, Form obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public Form __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public FlatData.MoveEnd? MoveEndOffset { get { int o = __p.__offset(4); return o != 0 ? (FlatData.MoveEnd?)(new FlatData.MoveEnd()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }
  public FlatData.Motion? PublicSkillOffset { get { int o = __p.__offset(6); return o != 0 ? (FlatData.Motion?)(new FlatData.Motion()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }

  public static Offset<FlatData.Form> CreateForm(FlatBufferBuilder builder,
      Offset<FlatData.MoveEnd> MoveEndOffsetOffset = default(Offset<FlatData.MoveEnd>),
      Offset<FlatData.Motion> PublicSkillOffsetOffset = default(Offset<FlatData.Motion>)) {
    builder.StartTable(2);
    Form.AddPublicSkillOffset(builder, PublicSkillOffsetOffset);
    Form.AddMoveEndOffset(builder, MoveEndOffsetOffset);
    return Form.EndForm(builder);
  }

  public static void StartForm(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddMoveEndOffset(FlatBufferBuilder builder, Offset<FlatData.MoveEnd> moveEndOffsetOffset) { builder.AddOffset(0, moveEndOffsetOffset.Value, 0); }
  public static void AddPublicSkillOffset(FlatBufferBuilder builder, Offset<FlatData.Motion> publicSkillOffsetOffset) { builder.AddOffset(1, publicSkillOffsetOffset.Value, 0); }
  public static Offset<FlatData.Form> EndForm(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<FlatData.Form>(o);
  }
}


static public class FormVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyTable(tablePos, 4 /*MoveEndOffset*/, FlatData.MoveEndVerify.Verify, false)
      && verifier.VerifyTable(tablePos, 6 /*PublicSkillOffset*/, FlatData.MotionVerify.Verify, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
