// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace FlatData
{

public enum FurnitureFunctionType : int
{
  None = 0,
  EventCollection = 1,
  VideoPlay = 2,
  TrophyCollection = 3,
  InteractionBGMPlay = 4,
};


}
