// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace FlatData
{

public enum GachaTicketType : int
{
  None = 0,
  PackageThreeStar = 1,
  ThreeStar = 2,
  TwoStar = 3,
  Normal = 4,
  NormalOnce = 5,
  StartDash = 6,
  SelectRecruit = 7,
  PackagePropertyThreeStar = 8,
  Temp_1 = 9,
  PackageAcademyThreeStar = 10,
};


}
