// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace FlatData
{

public enum GroundNodeType : int
{
  None = 0,
  WalkAble = 1,
  JumpAble = 2,
  TSSOnly = 3,
  NotWalkAble = 2147483647,
};


}
