// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace FlatData
{

public enum ItemCategory : int
{
  Coin = 0,
  CharacterExpGrowth = 1,
  SecretStone = 2,
  Material = 3,
  Consumable = 4,
  Collectible = 5,
  Favor = 6,
  RecruitCoin = 7,
  MonthlyBonus = 8,
  InvisibleToken = 9,
};


}
