// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace FlatData
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct LocalizeSkillExcel : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static LocalizeSkillExcel GetRootAsLocalizeSkillExcel(ByteBuffer _bb) { return GetRootAsLocalizeSkillExcel(_bb, new LocalizeSkillExcel()); }
  public static LocalizeSkillExcel GetRootAsLocalizeSkillExcel(ByteBuffer _bb, LocalizeSkillExcel obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public LocalizeSkillExcel __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public uint Key { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public string NameKr { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetNameKrBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetNameKrBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetNameKrArray() { return __p.__vector_as_array<byte>(6); }
  public string DescriptionKr { get { int o = __p.__offset(8); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetDescriptionKrBytes() { return __p.__vector_as_span<byte>(8, 1); }
#else
  public ArraySegment<byte>? GetDescriptionKrBytes() { return __p.__vector_as_arraysegment(8); }
#endif
  public byte[] GetDescriptionKrArray() { return __p.__vector_as_array<byte>(8); }
  public string SkillInvokeLocalizeKr { get { int o = __p.__offset(10); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetSkillInvokeLocalizeKrBytes() { return __p.__vector_as_span<byte>(10, 1); }
#else
  public ArraySegment<byte>? GetSkillInvokeLocalizeKrBytes() { return __p.__vector_as_arraysegment(10); }
#endif
  public byte[] GetSkillInvokeLocalizeKrArray() { return __p.__vector_as_array<byte>(10); }
  public string NameJp { get { int o = __p.__offset(12); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetNameJpBytes() { return __p.__vector_as_span<byte>(12, 1); }
#else
  public ArraySegment<byte>? GetNameJpBytes() { return __p.__vector_as_arraysegment(12); }
#endif
  public byte[] GetNameJpArray() { return __p.__vector_as_array<byte>(12); }
  public string DescriptionJp { get { int o = __p.__offset(14); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetDescriptionJpBytes() { return __p.__vector_as_span<byte>(14, 1); }
#else
  public ArraySegment<byte>? GetDescriptionJpBytes() { return __p.__vector_as_arraysegment(14); }
#endif
  public byte[] GetDescriptionJpArray() { return __p.__vector_as_array<byte>(14); }
  public string SkillInvokeLocalizeJp { get { int o = __p.__offset(16); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetSkillInvokeLocalizeJpBytes() { return __p.__vector_as_span<byte>(16, 1); }
#else
  public ArraySegment<byte>? GetSkillInvokeLocalizeJpBytes() { return __p.__vector_as_arraysegment(16); }
#endif
  public byte[] GetSkillInvokeLocalizeJpArray() { return __p.__vector_as_array<byte>(16); }
  public string NameTh { get { int o = __p.__offset(18); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetNameThBytes() { return __p.__vector_as_span<byte>(18, 1); }
#else
  public ArraySegment<byte>? GetNameThBytes() { return __p.__vector_as_arraysegment(18); }
#endif
  public byte[] GetNameThArray() { return __p.__vector_as_array<byte>(18); }
  public string DescriptionTh { get { int o = __p.__offset(20); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetDescriptionThBytes() { return __p.__vector_as_span<byte>(20, 1); }
#else
  public ArraySegment<byte>? GetDescriptionThBytes() { return __p.__vector_as_arraysegment(20); }
#endif
  public byte[] GetDescriptionThArray() { return __p.__vector_as_array<byte>(20); }
  public string SkillInvokeLocalizeTh { get { int o = __p.__offset(22); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetSkillInvokeLocalizeThBytes() { return __p.__vector_as_span<byte>(22, 1); }
#else
  public ArraySegment<byte>? GetSkillInvokeLocalizeThBytes() { return __p.__vector_as_arraysegment(22); }
#endif
  public byte[] GetSkillInvokeLocalizeThArray() { return __p.__vector_as_array<byte>(22); }
  public string NameTw { get { int o = __p.__offset(24); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetNameTwBytes() { return __p.__vector_as_span<byte>(24, 1); }
#else
  public ArraySegment<byte>? GetNameTwBytes() { return __p.__vector_as_arraysegment(24); }
#endif
  public byte[] GetNameTwArray() { return __p.__vector_as_array<byte>(24); }
  public string DescriptionTw { get { int o = __p.__offset(26); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetDescriptionTwBytes() { return __p.__vector_as_span<byte>(26, 1); }
#else
  public ArraySegment<byte>? GetDescriptionTwBytes() { return __p.__vector_as_arraysegment(26); }
#endif
  public byte[] GetDescriptionTwArray() { return __p.__vector_as_array<byte>(26); }
  public string SkillInvokeLocalizeTw { get { int o = __p.__offset(28); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetSkillInvokeLocalizeTwBytes() { return __p.__vector_as_span<byte>(28, 1); }
#else
  public ArraySegment<byte>? GetSkillInvokeLocalizeTwBytes() { return __p.__vector_as_arraysegment(28); }
#endif
  public byte[] GetSkillInvokeLocalizeTwArray() { return __p.__vector_as_array<byte>(28); }
  public string NameEn { get { int o = __p.__offset(30); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetNameEnBytes() { return __p.__vector_as_span<byte>(30, 1); }
#else
  public ArraySegment<byte>? GetNameEnBytes() { return __p.__vector_as_arraysegment(30); }
#endif
  public byte[] GetNameEnArray() { return __p.__vector_as_array<byte>(30); }
  public string DescriptionEn { get { int o = __p.__offset(32); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetDescriptionEnBytes() { return __p.__vector_as_span<byte>(32, 1); }
#else
  public ArraySegment<byte>? GetDescriptionEnBytes() { return __p.__vector_as_arraysegment(32); }
#endif
  public byte[] GetDescriptionEnArray() { return __p.__vector_as_array<byte>(32); }
  public string SkillInvokeLocalizeEn { get { int o = __p.__offset(34); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetSkillInvokeLocalizeEnBytes() { return __p.__vector_as_span<byte>(34, 1); }
#else
  public ArraySegment<byte>? GetSkillInvokeLocalizeEnBytes() { return __p.__vector_as_arraysegment(34); }
#endif
  public byte[] GetSkillInvokeLocalizeEnArray() { return __p.__vector_as_array<byte>(34); }

  public static Offset<FlatData.LocalizeSkillExcel> CreateLocalizeSkillExcel(FlatBufferBuilder builder,
      uint Key = 0,
      StringOffset NameKrOffset = default(StringOffset),
      StringOffset DescriptionKrOffset = default(StringOffset),
      StringOffset SkillInvokeLocalizeKrOffset = default(StringOffset),
      StringOffset NameJpOffset = default(StringOffset),
      StringOffset DescriptionJpOffset = default(StringOffset),
      StringOffset SkillInvokeLocalizeJpOffset = default(StringOffset),
      StringOffset NameThOffset = default(StringOffset),
      StringOffset DescriptionThOffset = default(StringOffset),
      StringOffset SkillInvokeLocalizeThOffset = default(StringOffset),
      StringOffset NameTwOffset = default(StringOffset),
      StringOffset DescriptionTwOffset = default(StringOffset),
      StringOffset SkillInvokeLocalizeTwOffset = default(StringOffset),
      StringOffset NameEnOffset = default(StringOffset),
      StringOffset DescriptionEnOffset = default(StringOffset),
      StringOffset SkillInvokeLocalizeEnOffset = default(StringOffset)) {
    builder.StartTable(16);
    LocalizeSkillExcel.AddSkillInvokeLocalizeEn(builder, SkillInvokeLocalizeEnOffset);
    LocalizeSkillExcel.AddDescriptionEn(builder, DescriptionEnOffset);
    LocalizeSkillExcel.AddNameEn(builder, NameEnOffset);
    LocalizeSkillExcel.AddSkillInvokeLocalizeTw(builder, SkillInvokeLocalizeTwOffset);
    LocalizeSkillExcel.AddDescriptionTw(builder, DescriptionTwOffset);
    LocalizeSkillExcel.AddNameTw(builder, NameTwOffset);
    LocalizeSkillExcel.AddSkillInvokeLocalizeTh(builder, SkillInvokeLocalizeThOffset);
    LocalizeSkillExcel.AddDescriptionTh(builder, DescriptionThOffset);
    LocalizeSkillExcel.AddNameTh(builder, NameThOffset);
    LocalizeSkillExcel.AddSkillInvokeLocalizeJp(builder, SkillInvokeLocalizeJpOffset);
    LocalizeSkillExcel.AddDescriptionJp(builder, DescriptionJpOffset);
    LocalizeSkillExcel.AddNameJp(builder, NameJpOffset);
    LocalizeSkillExcel.AddSkillInvokeLocalizeKr(builder, SkillInvokeLocalizeKrOffset);
    LocalizeSkillExcel.AddDescriptionKr(builder, DescriptionKrOffset);
    LocalizeSkillExcel.AddNameKr(builder, NameKrOffset);
    LocalizeSkillExcel.AddKey(builder, Key);
    return LocalizeSkillExcel.EndLocalizeSkillExcel(builder);
  }

  public static void StartLocalizeSkillExcel(FlatBufferBuilder builder) { builder.StartTable(16); }
  public static void AddKey(FlatBufferBuilder builder, uint key) { builder.AddUint(0, key, 0); }
  public static void AddNameKr(FlatBufferBuilder builder, StringOffset nameKrOffset) { builder.AddOffset(1, nameKrOffset.Value, 0); }
  public static void AddDescriptionKr(FlatBufferBuilder builder, StringOffset descriptionKrOffset) { builder.AddOffset(2, descriptionKrOffset.Value, 0); }
  public static void AddSkillInvokeLocalizeKr(FlatBufferBuilder builder, StringOffset skillInvokeLocalizeKrOffset) { builder.AddOffset(3, skillInvokeLocalizeKrOffset.Value, 0); }
  public static void AddNameJp(FlatBufferBuilder builder, StringOffset nameJpOffset) { builder.AddOffset(4, nameJpOffset.Value, 0); }
  public static void AddDescriptionJp(FlatBufferBuilder builder, StringOffset descriptionJpOffset) { builder.AddOffset(5, descriptionJpOffset.Value, 0); }
  public static void AddSkillInvokeLocalizeJp(FlatBufferBuilder builder, StringOffset skillInvokeLocalizeJpOffset) { builder.AddOffset(6, skillInvokeLocalizeJpOffset.Value, 0); }
  public static void AddNameTh(FlatBufferBuilder builder, StringOffset nameThOffset) { builder.AddOffset(7, nameThOffset.Value, 0); }
  public static void AddDescriptionTh(FlatBufferBuilder builder, StringOffset descriptionThOffset) { builder.AddOffset(8, descriptionThOffset.Value, 0); }
  public static void AddSkillInvokeLocalizeTh(FlatBufferBuilder builder, StringOffset skillInvokeLocalizeThOffset) { builder.AddOffset(9, skillInvokeLocalizeThOffset.Value, 0); }
  public static void AddNameTw(FlatBufferBuilder builder, StringOffset nameTwOffset) { builder.AddOffset(10, nameTwOffset.Value, 0); }
  public static void AddDescriptionTw(FlatBufferBuilder builder, StringOffset descriptionTwOffset) { builder.AddOffset(11, descriptionTwOffset.Value, 0); }
  public static void AddSkillInvokeLocalizeTw(FlatBufferBuilder builder, StringOffset skillInvokeLocalizeTwOffset) { builder.AddOffset(12, skillInvokeLocalizeTwOffset.Value, 0); }
  public static void AddNameEn(FlatBufferBuilder builder, StringOffset nameEnOffset) { builder.AddOffset(13, nameEnOffset.Value, 0); }
  public static void AddDescriptionEn(FlatBufferBuilder builder, StringOffset descriptionEnOffset) { builder.AddOffset(14, descriptionEnOffset.Value, 0); }
  public static void AddSkillInvokeLocalizeEn(FlatBufferBuilder builder, StringOffset skillInvokeLocalizeEnOffset) { builder.AddOffset(15, skillInvokeLocalizeEnOffset.Value, 0); }
  public static Offset<FlatData.LocalizeSkillExcel> EndLocalizeSkillExcel(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<FlatData.LocalizeSkillExcel>(o);
  }
}


static public class LocalizeSkillExcelVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Key*/, 4 /*uint*/, 4, false)
      && verifier.VerifyString(tablePos, 6 /*NameKr*/, false)
      && verifier.VerifyString(tablePos, 8 /*DescriptionKr*/, false)
      && verifier.VerifyString(tablePos, 10 /*SkillInvokeLocalizeKr*/, false)
      && verifier.VerifyString(tablePos, 12 /*NameJp*/, false)
      && verifier.VerifyString(tablePos, 14 /*DescriptionJp*/, false)
      && verifier.VerifyString(tablePos, 16 /*SkillInvokeLocalizeJp*/, false)
      && verifier.VerifyString(tablePos, 18 /*NameTh*/, false)
      && verifier.VerifyString(tablePos, 20 /*DescriptionTh*/, false)
      && verifier.VerifyString(tablePos, 22 /*SkillInvokeLocalizeTh*/, false)
      && verifier.VerifyString(tablePos, 24 /*NameTw*/, false)
      && verifier.VerifyString(tablePos, 26 /*DescriptionTw*/, false)
      && verifier.VerifyString(tablePos, 28 /*SkillInvokeLocalizeTw*/, false)
      && verifier.VerifyString(tablePos, 30 /*NameEn*/, false)
      && verifier.VerifyString(tablePos, 32 /*DescriptionEn*/, false)
      && verifier.VerifyString(tablePos, 34 /*SkillInvokeLocalizeEn*/, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
