// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace FlatData
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct LocalizeGachaShopExcel : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static LocalizeGachaShopExcel GetRootAsLocalizeGachaShopExcel(ByteBuffer _bb) { return GetRootAsLocalizeGachaShopExcel(_bb, new LocalizeGachaShopExcel()); }
  public static LocalizeGachaShopExcel GetRootAsLocalizeGachaShopExcel(ByteBuffer _bb, LocalizeGachaShopExcel obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public LocalizeGachaShopExcel __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long GachaShopId { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public string TabNameKr { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetTabNameKrBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetTabNameKrBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetTabNameKrArray() { return __p.__vector_as_array<byte>(6); }
  public string TabNameJp { get { int o = __p.__offset(8); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetTabNameJpBytes() { return __p.__vector_as_span<byte>(8, 1); }
#else
  public ArraySegment<byte>? GetTabNameJpBytes() { return __p.__vector_as_arraysegment(8); }
#endif
  public byte[] GetTabNameJpArray() { return __p.__vector_as_array<byte>(8); }
  public string TabNameTh { get { int o = __p.__offset(10); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetTabNameThBytes() { return __p.__vector_as_span<byte>(10, 1); }
#else
  public ArraySegment<byte>? GetTabNameThBytes() { return __p.__vector_as_arraysegment(10); }
#endif
  public byte[] GetTabNameThArray() { return __p.__vector_as_array<byte>(10); }
  public string TabNameTw { get { int o = __p.__offset(12); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetTabNameTwBytes() { return __p.__vector_as_span<byte>(12, 1); }
#else
  public ArraySegment<byte>? GetTabNameTwBytes() { return __p.__vector_as_arraysegment(12); }
#endif
  public byte[] GetTabNameTwArray() { return __p.__vector_as_array<byte>(12); }
  public string TabNameEn { get { int o = __p.__offset(14); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetTabNameEnBytes() { return __p.__vector_as_span<byte>(14, 1); }
#else
  public ArraySegment<byte>? GetTabNameEnBytes() { return __p.__vector_as_arraysegment(14); }
#endif
  public byte[] GetTabNameEnArray() { return __p.__vector_as_array<byte>(14); }
  public string TitleNameKr { get { int o = __p.__offset(16); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetTitleNameKrBytes() { return __p.__vector_as_span<byte>(16, 1); }
#else
  public ArraySegment<byte>? GetTitleNameKrBytes() { return __p.__vector_as_arraysegment(16); }
#endif
  public byte[] GetTitleNameKrArray() { return __p.__vector_as_array<byte>(16); }
  public string TitleNameJp { get { int o = __p.__offset(18); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetTitleNameJpBytes() { return __p.__vector_as_span<byte>(18, 1); }
#else
  public ArraySegment<byte>? GetTitleNameJpBytes() { return __p.__vector_as_arraysegment(18); }
#endif
  public byte[] GetTitleNameJpArray() { return __p.__vector_as_array<byte>(18); }
  public string TitleNameTh { get { int o = __p.__offset(20); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetTitleNameThBytes() { return __p.__vector_as_span<byte>(20, 1); }
#else
  public ArraySegment<byte>? GetTitleNameThBytes() { return __p.__vector_as_arraysegment(20); }
#endif
  public byte[] GetTitleNameThArray() { return __p.__vector_as_array<byte>(20); }
  public string TitleNameTw { get { int o = __p.__offset(22); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetTitleNameTwBytes() { return __p.__vector_as_span<byte>(22, 1); }
#else
  public ArraySegment<byte>? GetTitleNameTwBytes() { return __p.__vector_as_arraysegment(22); }
#endif
  public byte[] GetTitleNameTwArray() { return __p.__vector_as_array<byte>(22); }
  public string TitleNameEn { get { int o = __p.__offset(24); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetTitleNameEnBytes() { return __p.__vector_as_span<byte>(24, 1); }
#else
  public ArraySegment<byte>? GetTitleNameEnBytes() { return __p.__vector_as_arraysegment(24); }
#endif
  public byte[] GetTitleNameEnArray() { return __p.__vector_as_array<byte>(24); }
  public string SubTitleKr { get { int o = __p.__offset(26); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetSubTitleKrBytes() { return __p.__vector_as_span<byte>(26, 1); }
#else
  public ArraySegment<byte>? GetSubTitleKrBytes() { return __p.__vector_as_arraysegment(26); }
#endif
  public byte[] GetSubTitleKrArray() { return __p.__vector_as_array<byte>(26); }
  public string SubTitleJp { get { int o = __p.__offset(28); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetSubTitleJpBytes() { return __p.__vector_as_span<byte>(28, 1); }
#else
  public ArraySegment<byte>? GetSubTitleJpBytes() { return __p.__vector_as_arraysegment(28); }
#endif
  public byte[] GetSubTitleJpArray() { return __p.__vector_as_array<byte>(28); }
  public string SubTitleTh { get { int o = __p.__offset(30); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetSubTitleThBytes() { return __p.__vector_as_span<byte>(30, 1); }
#else
  public ArraySegment<byte>? GetSubTitleThBytes() { return __p.__vector_as_arraysegment(30); }
#endif
  public byte[] GetSubTitleThArray() { return __p.__vector_as_array<byte>(30); }
  public string SubTitleTw { get { int o = __p.__offset(32); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetSubTitleTwBytes() { return __p.__vector_as_span<byte>(32, 1); }
#else
  public ArraySegment<byte>? GetSubTitleTwBytes() { return __p.__vector_as_arraysegment(32); }
#endif
  public byte[] GetSubTitleTwArray() { return __p.__vector_as_array<byte>(32); }
  public string SubTitleEn { get { int o = __p.__offset(34); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetSubTitleEnBytes() { return __p.__vector_as_span<byte>(34, 1); }
#else
  public ArraySegment<byte>? GetSubTitleEnBytes() { return __p.__vector_as_arraysegment(34); }
#endif
  public byte[] GetSubTitleEnArray() { return __p.__vector_as_array<byte>(34); }
  public string GachaDescriptionKr { get { int o = __p.__offset(36); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetGachaDescriptionKrBytes() { return __p.__vector_as_span<byte>(36, 1); }
#else
  public ArraySegment<byte>? GetGachaDescriptionKrBytes() { return __p.__vector_as_arraysegment(36); }
#endif
  public byte[] GetGachaDescriptionKrArray() { return __p.__vector_as_array<byte>(36); }
  public string GachaDescriptionJp { get { int o = __p.__offset(38); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetGachaDescriptionJpBytes() { return __p.__vector_as_span<byte>(38, 1); }
#else
  public ArraySegment<byte>? GetGachaDescriptionJpBytes() { return __p.__vector_as_arraysegment(38); }
#endif
  public byte[] GetGachaDescriptionJpArray() { return __p.__vector_as_array<byte>(38); }
  public string GachaDescriptionTh { get { int o = __p.__offset(40); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetGachaDescriptionThBytes() { return __p.__vector_as_span<byte>(40, 1); }
#else
  public ArraySegment<byte>? GetGachaDescriptionThBytes() { return __p.__vector_as_arraysegment(40); }
#endif
  public byte[] GetGachaDescriptionThArray() { return __p.__vector_as_array<byte>(40); }
  public string GachaDescriptionTw { get { int o = __p.__offset(42); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetGachaDescriptionTwBytes() { return __p.__vector_as_span<byte>(42, 1); }
#else
  public ArraySegment<byte>? GetGachaDescriptionTwBytes() { return __p.__vector_as_arraysegment(42); }
#endif
  public byte[] GetGachaDescriptionTwArray() { return __p.__vector_as_array<byte>(42); }
  public string GachaDescriptionEn { get { int o = __p.__offset(44); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetGachaDescriptionEnBytes() { return __p.__vector_as_span<byte>(44, 1); }
#else
  public ArraySegment<byte>? GetGachaDescriptionEnBytes() { return __p.__vector_as_arraysegment(44); }
#endif
  public byte[] GetGachaDescriptionEnArray() { return __p.__vector_as_array<byte>(44); }

  public static Offset<FlatData.LocalizeGachaShopExcel> CreateLocalizeGachaShopExcel(FlatBufferBuilder builder,
      long GachaShopId = 0,
      StringOffset TabNameKrOffset = default(StringOffset),
      StringOffset TabNameJpOffset = default(StringOffset),
      StringOffset TabNameThOffset = default(StringOffset),
      StringOffset TabNameTwOffset = default(StringOffset),
      StringOffset TabNameEnOffset = default(StringOffset),
      StringOffset TitleNameKrOffset = default(StringOffset),
      StringOffset TitleNameJpOffset = default(StringOffset),
      StringOffset TitleNameThOffset = default(StringOffset),
      StringOffset TitleNameTwOffset = default(StringOffset),
      StringOffset TitleNameEnOffset = default(StringOffset),
      StringOffset SubTitleKrOffset = default(StringOffset),
      StringOffset SubTitleJpOffset = default(StringOffset),
      StringOffset SubTitleThOffset = default(StringOffset),
      StringOffset SubTitleTwOffset = default(StringOffset),
      StringOffset SubTitleEnOffset = default(StringOffset),
      StringOffset GachaDescriptionKrOffset = default(StringOffset),
      StringOffset GachaDescriptionJpOffset = default(StringOffset),
      StringOffset GachaDescriptionThOffset = default(StringOffset),
      StringOffset GachaDescriptionTwOffset = default(StringOffset),
      StringOffset GachaDescriptionEnOffset = default(StringOffset)) {
    builder.StartTable(21);
    LocalizeGachaShopExcel.AddGachaShopId(builder, GachaShopId);
    LocalizeGachaShopExcel.AddGachaDescriptionEn(builder, GachaDescriptionEnOffset);
    LocalizeGachaShopExcel.AddGachaDescriptionTw(builder, GachaDescriptionTwOffset);
    LocalizeGachaShopExcel.AddGachaDescriptionTh(builder, GachaDescriptionThOffset);
    LocalizeGachaShopExcel.AddGachaDescriptionJp(builder, GachaDescriptionJpOffset);
    LocalizeGachaShopExcel.AddGachaDescriptionKr(builder, GachaDescriptionKrOffset);
    LocalizeGachaShopExcel.AddSubTitleEn(builder, SubTitleEnOffset);
    LocalizeGachaShopExcel.AddSubTitleTw(builder, SubTitleTwOffset);
    LocalizeGachaShopExcel.AddSubTitleTh(builder, SubTitleThOffset);
    LocalizeGachaShopExcel.AddSubTitleJp(builder, SubTitleJpOffset);
    LocalizeGachaShopExcel.AddSubTitleKr(builder, SubTitleKrOffset);
    LocalizeGachaShopExcel.AddTitleNameEn(builder, TitleNameEnOffset);
    LocalizeGachaShopExcel.AddTitleNameTw(builder, TitleNameTwOffset);
    LocalizeGachaShopExcel.AddTitleNameTh(builder, TitleNameThOffset);
    LocalizeGachaShopExcel.AddTitleNameJp(builder, TitleNameJpOffset);
    LocalizeGachaShopExcel.AddTitleNameKr(builder, TitleNameKrOffset);
    LocalizeGachaShopExcel.AddTabNameEn(builder, TabNameEnOffset);
    LocalizeGachaShopExcel.AddTabNameTw(builder, TabNameTwOffset);
    LocalizeGachaShopExcel.AddTabNameTh(builder, TabNameThOffset);
    LocalizeGachaShopExcel.AddTabNameJp(builder, TabNameJpOffset);
    LocalizeGachaShopExcel.AddTabNameKr(builder, TabNameKrOffset);
    return LocalizeGachaShopExcel.EndLocalizeGachaShopExcel(builder);
  }

  public static void StartLocalizeGachaShopExcel(FlatBufferBuilder builder) { builder.StartTable(21); }
  public static void AddGachaShopId(FlatBufferBuilder builder, long gachaShopId) { builder.AddLong(0, gachaShopId, 0); }
  public static void AddTabNameKr(FlatBufferBuilder builder, StringOffset tabNameKrOffset) { builder.AddOffset(1, tabNameKrOffset.Value, 0); }
  public static void AddTabNameJp(FlatBufferBuilder builder, StringOffset tabNameJpOffset) { builder.AddOffset(2, tabNameJpOffset.Value, 0); }
  public static void AddTabNameTh(FlatBufferBuilder builder, StringOffset tabNameThOffset) { builder.AddOffset(3, tabNameThOffset.Value, 0); }
  public static void AddTabNameTw(FlatBufferBuilder builder, StringOffset tabNameTwOffset) { builder.AddOffset(4, tabNameTwOffset.Value, 0); }
  public static void AddTabNameEn(FlatBufferBuilder builder, StringOffset tabNameEnOffset) { builder.AddOffset(5, tabNameEnOffset.Value, 0); }
  public static void AddTitleNameKr(FlatBufferBuilder builder, StringOffset titleNameKrOffset) { builder.AddOffset(6, titleNameKrOffset.Value, 0); }
  public static void AddTitleNameJp(FlatBufferBuilder builder, StringOffset titleNameJpOffset) { builder.AddOffset(7, titleNameJpOffset.Value, 0); }
  public static void AddTitleNameTh(FlatBufferBuilder builder, StringOffset titleNameThOffset) { builder.AddOffset(8, titleNameThOffset.Value, 0); }
  public static void AddTitleNameTw(FlatBufferBuilder builder, StringOffset titleNameTwOffset) { builder.AddOffset(9, titleNameTwOffset.Value, 0); }
  public static void AddTitleNameEn(FlatBufferBuilder builder, StringOffset titleNameEnOffset) { builder.AddOffset(10, titleNameEnOffset.Value, 0); }
  public static void AddSubTitleKr(FlatBufferBuilder builder, StringOffset subTitleKrOffset) { builder.AddOffset(11, subTitleKrOffset.Value, 0); }
  public static void AddSubTitleJp(FlatBufferBuilder builder, StringOffset subTitleJpOffset) { builder.AddOffset(12, subTitleJpOffset.Value, 0); }
  public static void AddSubTitleTh(FlatBufferBuilder builder, StringOffset subTitleThOffset) { builder.AddOffset(13, subTitleThOffset.Value, 0); }
  public static void AddSubTitleTw(FlatBufferBuilder builder, StringOffset subTitleTwOffset) { builder.AddOffset(14, subTitleTwOffset.Value, 0); }
  public static void AddSubTitleEn(FlatBufferBuilder builder, StringOffset subTitleEnOffset) { builder.AddOffset(15, subTitleEnOffset.Value, 0); }
  public static void AddGachaDescriptionKr(FlatBufferBuilder builder, StringOffset gachaDescriptionKrOffset) { builder.AddOffset(16, gachaDescriptionKrOffset.Value, 0); }
  public static void AddGachaDescriptionJp(FlatBufferBuilder builder, StringOffset gachaDescriptionJpOffset) { builder.AddOffset(17, gachaDescriptionJpOffset.Value, 0); }
  public static void AddGachaDescriptionTh(FlatBufferBuilder builder, StringOffset gachaDescriptionThOffset) { builder.AddOffset(18, gachaDescriptionThOffset.Value, 0); }
  public static void AddGachaDescriptionTw(FlatBufferBuilder builder, StringOffset gachaDescriptionTwOffset) { builder.AddOffset(19, gachaDescriptionTwOffset.Value, 0); }
  public static void AddGachaDescriptionEn(FlatBufferBuilder builder, StringOffset gachaDescriptionEnOffset) { builder.AddOffset(20, gachaDescriptionEnOffset.Value, 0); }
  public static Offset<FlatData.LocalizeGachaShopExcel> EndLocalizeGachaShopExcel(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<FlatData.LocalizeGachaShopExcel>(o);
  }
}


static public class LocalizeGachaShopExcelVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*GachaShopId*/, 8 /*long*/, 8, false)
      && verifier.VerifyString(tablePos, 6 /*TabNameKr*/, false)
      && verifier.VerifyString(tablePos, 8 /*TabNameJp*/, false)
      && verifier.VerifyString(tablePos, 10 /*TabNameTh*/, false)
      && verifier.VerifyString(tablePos, 12 /*TabNameTw*/, false)
      && verifier.VerifyString(tablePos, 14 /*TabNameEn*/, false)
      && verifier.VerifyString(tablePos, 16 /*TitleNameKr*/, false)
      && verifier.VerifyString(tablePos, 18 /*TitleNameJp*/, false)
      && verifier.VerifyString(tablePos, 20 /*TitleNameTh*/, false)
      && verifier.VerifyString(tablePos, 22 /*TitleNameTw*/, false)
      && verifier.VerifyString(tablePos, 24 /*TitleNameEn*/, false)
      && verifier.VerifyString(tablePos, 26 /*SubTitleKr*/, false)
      && verifier.VerifyString(tablePos, 28 /*SubTitleJp*/, false)
      && verifier.VerifyString(tablePos, 30 /*SubTitleTh*/, false)
      && verifier.VerifyString(tablePos, 32 /*SubTitleTw*/, false)
      && verifier.VerifyString(tablePos, 34 /*SubTitleEn*/, false)
      && verifier.VerifyString(tablePos, 36 /*GachaDescriptionKr*/, false)
      && verifier.VerifyString(tablePos, 38 /*GachaDescriptionJp*/, false)
      && verifier.VerifyString(tablePos, 40 /*GachaDescriptionTh*/, false)
      && verifier.VerifyString(tablePos, 42 /*GachaDescriptionTw*/, false)
      && verifier.VerifyString(tablePos, 44 /*GachaDescriptionEn*/, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
