// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace FlatData
{

public enum MailType : int
{
  System = 0,
  Attendance = 1,
  Event = 2,
  MassTrade = 3,
  InventoryFull = 4,
  ArenaDefenseVictory = 5,
  CouponUsageReward = 6,
  ArenaSeasonClose = 7,
  ProductReward = 8,
  MonthlyProductReward = 9,
  ExpiryChangeItem = 10,
  ClanAttendance = 11,
  AccountLink = 12,
  NewUserBonus = 13,
  LeftClanAssistReward = 14,
  CashShopBuy = 15,
  MonthlyProductPackage = 16,
  WebEventReward = 17,
  AttendanceImmediately = 18,
  WeeklyProductReward = 19,
  BiweeklyProductReward = 20,
  Temp_1 = 21,
  Temp_2 = 22,
  Temp_3 = 23,
  CouponCompleteReward = 24,
  BirthdayMail = 25,
  FromCS = 26,
  ExpiryChangeCurrency = 27,
};


}
