// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace FlatData
{

public enum MeetupConditionType : int
{
  None = 0,
  EventContentStageClear = 1,
  ScenarioClear = 2,
};


}
