// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace FlatData
{

public enum MessagePopupLayout : int
{
  TextOnly = 0,
  ImageBig = 1,
  ImageSmall = 2,
  UnlockCondition = 3,
};


}
