// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace FlatData
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct MiniGameDreamScheduleResultExcel : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static MiniGameDreamScheduleResultExcel GetRootAsMiniGameDreamScheduleResultExcel(ByteBuffer _bb) { return GetRootAsMiniGameDreamScheduleResultExcel(_bb, new MiniGameDreamScheduleResultExcel()); }
  public static MiniGameDreamScheduleResultExcel GetRootAsMiniGameDreamScheduleResultExcel(ByteBuffer _bb, MiniGameDreamScheduleResultExcel obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public MiniGameDreamScheduleResultExcel __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long Id { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public long EventContentId { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public FlatData.DreamMakerResult DreamMakerResult { get { int o = __p.__offset(8); return o != 0 ? (FlatData.DreamMakerResult)__p.bb.GetInt(o + __p.bb_pos) : FlatData.DreamMakerResult.None; } }
  public long DreamMakerScheduleGroup { get { int o = __p.__offset(10); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public int Prob { get { int o = __p.__offset(12); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public FlatData.DreamMakerParameterType RewardParameter(int j) { int o = __p.__offset(14); return o != 0 ? (FlatData.DreamMakerParameterType)__p.bb.GetInt(__p.__vector(o) + j * 4) : (FlatData.DreamMakerParameterType)0; }
  public int RewardParameterLength { get { int o = __p.__offset(14); return o != 0 ? __p.__vector_len(o) : 0; } }
#if ENABLE_SPAN_T
  public Span<FlatData.DreamMakerParameterType> GetRewardParameterBytes() { return __p.__vector_as_span<FlatData.DreamMakerParameterType>(14, 4); }
#else
  public ArraySegment<byte>? GetRewardParameterBytes() { return __p.__vector_as_arraysegment(14); }
#endif
  public FlatData.DreamMakerParameterType[] GetRewardParameterArray() { int o = __p.__offset(14); if (o == 0) return null; int p = __p.__vector(o); int l = __p.__vector_len(o); FlatData.DreamMakerParameterType[] a = new FlatData.DreamMakerParameterType[l]; for (int i = 0; i < l; i++) { a[i] = (FlatData.DreamMakerParameterType)__p.bb.GetInt(p + i * 4); } return a; }
  public FlatData.DreamMakerParamOperationType RewardParameterOperationType(int j) { int o = __p.__offset(16); return o != 0 ? (FlatData.DreamMakerParamOperationType)__p.bb.GetInt(__p.__vector(o) + j * 4) : (FlatData.DreamMakerParamOperationType)0; }
  public int RewardParameterOperationTypeLength { get { int o = __p.__offset(16); return o != 0 ? __p.__vector_len(o) : 0; } }
#if ENABLE_SPAN_T
  public Span<FlatData.DreamMakerParamOperationType> GetRewardParameterOperationTypeBytes() { return __p.__vector_as_span<FlatData.DreamMakerParamOperationType>(16, 4); }
#else
  public ArraySegment<byte>? GetRewardParameterOperationTypeBytes() { return __p.__vector_as_arraysegment(16); }
#endif
  public FlatData.DreamMakerParamOperationType[] GetRewardParameterOperationTypeArray() { int o = __p.__offset(16); if (o == 0) return null; int p = __p.__vector(o); int l = __p.__vector_len(o); FlatData.DreamMakerParamOperationType[] a = new FlatData.DreamMakerParamOperationType[l]; for (int i = 0; i < l; i++) { a[i] = (FlatData.DreamMakerParamOperationType)__p.bb.GetInt(p + i * 4); } return a; }
  public long RewardParameterAmount(int j) { int o = __p.__offset(18); return o != 0 ? __p.bb.GetLong(__p.__vector(o) + j * 8) : (long)0; }
  public int RewardParameterAmountLength { get { int o = __p.__offset(18); return o != 0 ? __p.__vector_len(o) : 0; } }
#if ENABLE_SPAN_T
  public Span<long> GetRewardParameterAmountBytes() { return __p.__vector_as_span<long>(18, 8); }
#else
  public ArraySegment<byte>? GetRewardParameterAmountBytes() { return __p.__vector_as_arraysegment(18); }
#endif
  public long[] GetRewardParameterAmountArray() { return __p.__vector_as_array<long>(18); }
  public FlatData.ParcelType RewardParcelType { get { int o = __p.__offset(20); return o != 0 ? (FlatData.ParcelType)__p.bb.GetInt(o + __p.bb_pos) : FlatData.ParcelType.None; } }
  public long RewardParcelId { get { int o = __p.__offset(22); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public long RewardParcelAmount { get { int o = __p.__offset(24); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }

  public static Offset<FlatData.MiniGameDreamScheduleResultExcel> CreateMiniGameDreamScheduleResultExcel(FlatBufferBuilder builder,
      long Id = 0,
      long EventContentId = 0,
      FlatData.DreamMakerResult DreamMakerResult = FlatData.DreamMakerResult.None,
      long DreamMakerScheduleGroup = 0,
      int Prob = 0,
      VectorOffset RewardParameterOffset = default(VectorOffset),
      VectorOffset RewardParameterOperationTypeOffset = default(VectorOffset),
      VectorOffset RewardParameterAmountOffset = default(VectorOffset),
      FlatData.ParcelType RewardParcelType = FlatData.ParcelType.None,
      long RewardParcelId = 0,
      long RewardParcelAmount = 0) {
    builder.StartTable(11);
    MiniGameDreamScheduleResultExcel.AddRewardParcelAmount(builder, RewardParcelAmount);
    MiniGameDreamScheduleResultExcel.AddRewardParcelId(builder, RewardParcelId);
    MiniGameDreamScheduleResultExcel.AddDreamMakerScheduleGroup(builder, DreamMakerScheduleGroup);
    MiniGameDreamScheduleResultExcel.AddEventContentId(builder, EventContentId);
    MiniGameDreamScheduleResultExcel.AddId(builder, Id);
    MiniGameDreamScheduleResultExcel.AddRewardParcelType(builder, RewardParcelType);
    MiniGameDreamScheduleResultExcel.AddRewardParameterAmount(builder, RewardParameterAmountOffset);
    MiniGameDreamScheduleResultExcel.AddRewardParameterOperationType(builder, RewardParameterOperationTypeOffset);
    MiniGameDreamScheduleResultExcel.AddRewardParameter(builder, RewardParameterOffset);
    MiniGameDreamScheduleResultExcel.AddProb(builder, Prob);
    MiniGameDreamScheduleResultExcel.AddDreamMakerResult(builder, DreamMakerResult);
    return MiniGameDreamScheduleResultExcel.EndMiniGameDreamScheduleResultExcel(builder);
  }

  public static void StartMiniGameDreamScheduleResultExcel(FlatBufferBuilder builder) { builder.StartTable(11); }
  public static void AddId(FlatBufferBuilder builder, long id) { builder.AddLong(0, id, 0); }
  public static void AddEventContentId(FlatBufferBuilder builder, long eventContentId) { builder.AddLong(1, eventContentId, 0); }
  public static void AddDreamMakerResult(FlatBufferBuilder builder, FlatData.DreamMakerResult dreamMakerResult) { builder.AddInt(2, (int)dreamMakerResult, 0); }
  public static void AddDreamMakerScheduleGroup(FlatBufferBuilder builder, long dreamMakerScheduleGroup) { builder.AddLong(3, dreamMakerScheduleGroup, 0); }
  public static void AddProb(FlatBufferBuilder builder, int prob) { builder.AddInt(4, prob, 0); }
  public static void AddRewardParameter(FlatBufferBuilder builder, VectorOffset rewardParameterOffset) { builder.AddOffset(5, rewardParameterOffset.Value, 0); }
  public static VectorOffset CreateRewardParameterVector(FlatBufferBuilder builder, FlatData.DreamMakerParameterType[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddInt((int)data[i]); return builder.EndVector(); }
  public static VectorOffset CreateRewardParameterVectorBlock(FlatBufferBuilder builder, FlatData.DreamMakerParameterType[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateRewardParameterVectorBlock(FlatBufferBuilder builder, ArraySegment<FlatData.DreamMakerParameterType> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateRewardParameterVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<FlatData.DreamMakerParameterType>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartRewardParameterVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddRewardParameterOperationType(FlatBufferBuilder builder, VectorOffset rewardParameterOperationTypeOffset) { builder.AddOffset(6, rewardParameterOperationTypeOffset.Value, 0); }
  public static VectorOffset CreateRewardParameterOperationTypeVector(FlatBufferBuilder builder, FlatData.DreamMakerParamOperationType[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddInt((int)data[i]); return builder.EndVector(); }
  public static VectorOffset CreateRewardParameterOperationTypeVectorBlock(FlatBufferBuilder builder, FlatData.DreamMakerParamOperationType[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateRewardParameterOperationTypeVectorBlock(FlatBufferBuilder builder, ArraySegment<FlatData.DreamMakerParamOperationType> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateRewardParameterOperationTypeVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<FlatData.DreamMakerParamOperationType>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartRewardParameterOperationTypeVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddRewardParameterAmount(FlatBufferBuilder builder, VectorOffset rewardParameterAmountOffset) { builder.AddOffset(7, rewardParameterAmountOffset.Value, 0); }
  public static VectorOffset CreateRewardParameterAmountVector(FlatBufferBuilder builder, long[] data) { builder.StartVector(8, data.Length, 8); for (int i = data.Length - 1; i >= 0; i--) builder.AddLong(data[i]); return builder.EndVector(); }
  public static VectorOffset CreateRewardParameterAmountVectorBlock(FlatBufferBuilder builder, long[] data) { builder.StartVector(8, data.Length, 8); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateRewardParameterAmountVectorBlock(FlatBufferBuilder builder, ArraySegment<long> data) { builder.StartVector(8, data.Count, 8); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateRewardParameterAmountVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<long>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartRewardParameterAmountVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(8, numElems, 8); }
  public static void AddRewardParcelType(FlatBufferBuilder builder, FlatData.ParcelType rewardParcelType) { builder.AddInt(8, (int)rewardParcelType, 0); }
  public static void AddRewardParcelId(FlatBufferBuilder builder, long rewardParcelId) { builder.AddLong(9, rewardParcelId, 0); }
  public static void AddRewardParcelAmount(FlatBufferBuilder builder, long rewardParcelAmount) { builder.AddLong(10, rewardParcelAmount, 0); }
  public static Offset<FlatData.MiniGameDreamScheduleResultExcel> EndMiniGameDreamScheduleResultExcel(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<FlatData.MiniGameDreamScheduleResultExcel>(o);
  }
}


static public class MiniGameDreamScheduleResultExcelVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Id*/, 8 /*long*/, 8, false)
      && verifier.VerifyField(tablePos, 6 /*EventContentId*/, 8 /*long*/, 8, false)
      && verifier.VerifyField(tablePos, 8 /*DreamMakerResult*/, 4 /*FlatData.DreamMakerResult*/, 4, false)
      && verifier.VerifyField(tablePos, 10 /*DreamMakerScheduleGroup*/, 8 /*long*/, 8, false)
      && verifier.VerifyField(tablePos, 12 /*Prob*/, 4 /*int*/, 4, false)
      && verifier.VerifyVectorOfData(tablePos, 14 /*RewardParameter*/, 4 /*FlatData.DreamMakerParameterType*/, false)
      && verifier.VerifyVectorOfData(tablePos, 16 /*RewardParameterOperationType*/, 4 /*FlatData.DreamMakerParamOperationType*/, false)
      && verifier.VerifyVectorOfData(tablePos, 18 /*RewardParameterAmount*/, 8 /*long*/, false)
      && verifier.VerifyField(tablePos, 20 /*RewardParcelType*/, 4 /*FlatData.ParcelType*/, 4, false)
      && verifier.VerifyField(tablePos, 22 /*RewardParcelId*/, 8 /*long*/, 8, false)
      && verifier.VerifyField(tablePos, 24 /*RewardParcelAmount*/, 8 /*long*/, 8, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
