// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace FlatData
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct MinigameTBGItemExcel : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static MinigameTBGItemExcel GetRootAsMinigameTBGItemExcel(ByteBuffer _bb) { return GetRootAsMinigameTBGItemExcel(_bb, new MinigameTBGItemExcel()); }
  public static MinigameTBGItemExcel GetRootAsMinigameTBGItemExcel(ByteBuffer _bb, MinigameTBGItemExcel obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public MinigameTBGItemExcel __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long UniqueId { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public FlatData.TBGItemType ItemType { get { int o = __p.__offset(6); return o != 0 ? (FlatData.TBGItemType)__p.bb.GetInt(o + __p.bb_pos) : FlatData.TBGItemType.None; } }
  public FlatData.TBGItemEffectType TBGItemEffectType { get { int o = __p.__offset(8); return o != 0 ? (FlatData.TBGItemEffectType)__p.bb.GetInt(o + __p.bb_pos) : FlatData.TBGItemEffectType.None; } }
  public int ItemParameter { get { int o = __p.__offset(10); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public string LocalizeETCId { get { int o = __p.__offset(12); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetLocalizeETCIdBytes() { return __p.__vector_as_span<byte>(12, 1); }
#else
  public ArraySegment<byte>? GetLocalizeETCIdBytes() { return __p.__vector_as_arraysegment(12); }
#endif
  public byte[] GetLocalizeETCIdArray() { return __p.__vector_as_array<byte>(12); }
  public string Icon { get { int o = __p.__offset(14); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetIconBytes() { return __p.__vector_as_span<byte>(14, 1); }
#else
  public ArraySegment<byte>? GetIconBytes() { return __p.__vector_as_arraysegment(14); }
#endif
  public byte[] GetIconArray() { return __p.__vector_as_array<byte>(14); }
  public string BuffIcon { get { int o = __p.__offset(16); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetBuffIconBytes() { return __p.__vector_as_span<byte>(16, 1); }
#else
  public ArraySegment<byte>? GetBuffIconBytes() { return __p.__vector_as_arraysegment(16); }
#endif
  public byte[] GetBuffIconArray() { return __p.__vector_as_array<byte>(16); }
  public int EncounterCount { get { int o = __p.__offset(18); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public string DiceEffectAniClip { get { int o = __p.__offset(20); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetDiceEffectAniClipBytes() { return __p.__vector_as_span<byte>(20, 1); }
#else
  public ArraySegment<byte>? GetDiceEffectAniClipBytes() { return __p.__vector_as_arraysegment(20); }
#endif
  public byte[] GetDiceEffectAniClipArray() { return __p.__vector_as_array<byte>(20); }
  public bool BuffIconHUDVisible { get { int o = __p.__offset(22); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }

  public static Offset<FlatData.MinigameTBGItemExcel> CreateMinigameTBGItemExcel(FlatBufferBuilder builder,
      long UniqueId = 0,
      FlatData.TBGItemType ItemType = FlatData.TBGItemType.None,
      FlatData.TBGItemEffectType TBGItemEffectType = FlatData.TBGItemEffectType.None,
      int ItemParameter = 0,
      StringOffset LocalizeETCIdOffset = default(StringOffset),
      StringOffset IconOffset = default(StringOffset),
      StringOffset BuffIconOffset = default(StringOffset),
      int EncounterCount = 0,
      StringOffset DiceEffectAniClipOffset = default(StringOffset),
      bool BuffIconHUDVisible = false) {
    builder.StartTable(10);
    MinigameTBGItemExcel.AddUniqueId(builder, UniqueId);
    MinigameTBGItemExcel.AddDiceEffectAniClip(builder, DiceEffectAniClipOffset);
    MinigameTBGItemExcel.AddEncounterCount(builder, EncounterCount);
    MinigameTBGItemExcel.AddBuffIcon(builder, BuffIconOffset);
    MinigameTBGItemExcel.AddIcon(builder, IconOffset);
    MinigameTBGItemExcel.AddLocalizeETCId(builder, LocalizeETCIdOffset);
    MinigameTBGItemExcel.AddItemParameter(builder, ItemParameter);
    MinigameTBGItemExcel.AddTBGItemEffectType(builder, TBGItemEffectType);
    MinigameTBGItemExcel.AddItemType(builder, ItemType);
    MinigameTBGItemExcel.AddBuffIconHUDVisible(builder, BuffIconHUDVisible);
    return MinigameTBGItemExcel.EndMinigameTBGItemExcel(builder);
  }

  public static void StartMinigameTBGItemExcel(FlatBufferBuilder builder) { builder.StartTable(10); }
  public static void AddUniqueId(FlatBufferBuilder builder, long uniqueId) { builder.AddLong(0, uniqueId, 0); }
  public static void AddItemType(FlatBufferBuilder builder, FlatData.TBGItemType itemType) { builder.AddInt(1, (int)itemType, 0); }
  public static void AddTBGItemEffectType(FlatBufferBuilder builder, FlatData.TBGItemEffectType tBGItemEffectType) { builder.AddInt(2, (int)tBGItemEffectType, 0); }
  public static void AddItemParameter(FlatBufferBuilder builder, int itemParameter) { builder.AddInt(3, itemParameter, 0); }
  public static void AddLocalizeETCId(FlatBufferBuilder builder, StringOffset localizeETCIdOffset) { builder.AddOffset(4, localizeETCIdOffset.Value, 0); }
  public static void AddIcon(FlatBufferBuilder builder, StringOffset iconOffset) { builder.AddOffset(5, iconOffset.Value, 0); }
  public static void AddBuffIcon(FlatBufferBuilder builder, StringOffset buffIconOffset) { builder.AddOffset(6, buffIconOffset.Value, 0); }
  public static void AddEncounterCount(FlatBufferBuilder builder, int encounterCount) { builder.AddInt(7, encounterCount, 0); }
  public static void AddDiceEffectAniClip(FlatBufferBuilder builder, StringOffset diceEffectAniClipOffset) { builder.AddOffset(8, diceEffectAniClipOffset.Value, 0); }
  public static void AddBuffIconHUDVisible(FlatBufferBuilder builder, bool buffIconHUDVisible) { builder.AddBool(9, buffIconHUDVisible, false); }
  public static Offset<FlatData.MinigameTBGItemExcel> EndMinigameTBGItemExcel(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<FlatData.MinigameTBGItemExcel>(o);
  }
}


static public class MinigameTBGItemExcelVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*UniqueId*/, 8 /*long*/, 8, false)
      && verifier.VerifyField(tablePos, 6 /*ItemType*/, 4 /*FlatData.TBGItemType*/, 4, false)
      && verifier.VerifyField(tablePos, 8 /*TBGItemEffectType*/, 4 /*FlatData.TBGItemEffectType*/, 4, false)
      && verifier.VerifyField(tablePos, 10 /*ItemParameter*/, 4 /*int*/, 4, false)
      && verifier.VerifyString(tablePos, 12 /*LocalizeETCId*/, false)
      && verifier.VerifyString(tablePos, 14 /*Icon*/, false)
      && verifier.VerifyString(tablePos, 16 /*BuffIcon*/, false)
      && verifier.VerifyField(tablePos, 18 /*EncounterCount*/, 4 /*int*/, 4, false)
      && verifier.VerifyString(tablePos, 20 /*DiceEffectAniClip*/, false)
      && verifier.VerifyField(tablePos, 22 /*BuffIconHUDVisible*/, 1 /*bool*/, 1, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
