// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace FlatData
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct MiniGameDefenseFixedStatExcel : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static MiniGameDefenseFixedStatExcel GetRootAsMiniGameDefenseFixedStatExcel(ByteBuffer _bb) { return GetRootAsMiniGameDefenseFixedStatExcel(_bb, new MiniGameDefenseFixedStatExcel()); }
  public static MiniGameDefenseFixedStatExcel GetRootAsMiniGameDefenseFixedStatExcel(ByteBuffer _bb, MiniGameDefenseFixedStatExcel obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public MiniGameDefenseFixedStatExcel __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long MinigameDefenseFixedStatId { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public int Level { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int Grade { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int ExSkillLevel { get { int o = __p.__offset(10); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int NoneExSkillLevel { get { int o = __p.__offset(12); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int Equipment1Tier { get { int o = __p.__offset(14); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int Equipment1level { get { int o = __p.__offset(16); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int Equipment2Tier { get { int o = __p.__offset(18); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int Equipment2level { get { int o = __p.__offset(20); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int Equipment3Tier { get { int o = __p.__offset(22); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int Equipment3level { get { int o = __p.__offset(24); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int CharacterWeaponGrade { get { int o = __p.__offset(26); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int CharacterWeaponLevel { get { int o = __p.__offset(28); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int CharacterGearTier { get { int o = __p.__offset(30); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int CharacterGearLevel { get { int o = __p.__offset(32); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

  public static Offset<FlatData.MiniGameDefenseFixedStatExcel> CreateMiniGameDefenseFixedStatExcel(FlatBufferBuilder builder,
      long MinigameDefenseFixedStatId = 0,
      int Level = 0,
      int Grade = 0,
      int ExSkillLevel = 0,
      int NoneExSkillLevel = 0,
      int Equipment1Tier = 0,
      int Equipment1level = 0,
      int Equipment2Tier = 0,
      int Equipment2level = 0,
      int Equipment3Tier = 0,
      int Equipment3level = 0,
      int CharacterWeaponGrade = 0,
      int CharacterWeaponLevel = 0,
      int CharacterGearTier = 0,
      int CharacterGearLevel = 0) {
    builder.StartTable(15);
    MiniGameDefenseFixedStatExcel.AddMinigameDefenseFixedStatId(builder, MinigameDefenseFixedStatId);
    MiniGameDefenseFixedStatExcel.AddCharacterGearLevel(builder, CharacterGearLevel);
    MiniGameDefenseFixedStatExcel.AddCharacterGearTier(builder, CharacterGearTier);
    MiniGameDefenseFixedStatExcel.AddCharacterWeaponLevel(builder, CharacterWeaponLevel);
    MiniGameDefenseFixedStatExcel.AddCharacterWeaponGrade(builder, CharacterWeaponGrade);
    MiniGameDefenseFixedStatExcel.AddEquipment3level(builder, Equipment3level);
    MiniGameDefenseFixedStatExcel.AddEquipment3Tier(builder, Equipment3Tier);
    MiniGameDefenseFixedStatExcel.AddEquipment2level(builder, Equipment2level);
    MiniGameDefenseFixedStatExcel.AddEquipment2Tier(builder, Equipment2Tier);
    MiniGameDefenseFixedStatExcel.AddEquipment1level(builder, Equipment1level);
    MiniGameDefenseFixedStatExcel.AddEquipment1Tier(builder, Equipment1Tier);
    MiniGameDefenseFixedStatExcel.AddNoneExSkillLevel(builder, NoneExSkillLevel);
    MiniGameDefenseFixedStatExcel.AddExSkillLevel(builder, ExSkillLevel);
    MiniGameDefenseFixedStatExcel.AddGrade(builder, Grade);
    MiniGameDefenseFixedStatExcel.AddLevel(builder, Level);
    return MiniGameDefenseFixedStatExcel.EndMiniGameDefenseFixedStatExcel(builder);
  }

  public static void StartMiniGameDefenseFixedStatExcel(FlatBufferBuilder builder) { builder.StartTable(15); }
  public static void AddMinigameDefenseFixedStatId(FlatBufferBuilder builder, long minigameDefenseFixedStatId) { builder.AddLong(0, minigameDefenseFixedStatId, 0); }
  public static void AddLevel(FlatBufferBuilder builder, int level) { builder.AddInt(1, level, 0); }
  public static void AddGrade(FlatBufferBuilder builder, int grade) { builder.AddInt(2, grade, 0); }
  public static void AddExSkillLevel(FlatBufferBuilder builder, int exSkillLevel) { builder.AddInt(3, exSkillLevel, 0); }
  public static void AddNoneExSkillLevel(FlatBufferBuilder builder, int noneExSkillLevel) { builder.AddInt(4, noneExSkillLevel, 0); }
  public static void AddEquipment1Tier(FlatBufferBuilder builder, int equipment1Tier) { builder.AddInt(5, equipment1Tier, 0); }
  public static void AddEquipment1level(FlatBufferBuilder builder, int equipment1level) { builder.AddInt(6, equipment1level, 0); }
  public static void AddEquipment2Tier(FlatBufferBuilder builder, int equipment2Tier) { builder.AddInt(7, equipment2Tier, 0); }
  public static void AddEquipment2level(FlatBufferBuilder builder, int equipment2level) { builder.AddInt(8, equipment2level, 0); }
  public static void AddEquipment3Tier(FlatBufferBuilder builder, int equipment3Tier) { builder.AddInt(9, equipment3Tier, 0); }
  public static void AddEquipment3level(FlatBufferBuilder builder, int equipment3level) { builder.AddInt(10, equipment3level, 0); }
  public static void AddCharacterWeaponGrade(FlatBufferBuilder builder, int characterWeaponGrade) { builder.AddInt(11, characterWeaponGrade, 0); }
  public static void AddCharacterWeaponLevel(FlatBufferBuilder builder, int characterWeaponLevel) { builder.AddInt(12, characterWeaponLevel, 0); }
  public static void AddCharacterGearTier(FlatBufferBuilder builder, int characterGearTier) { builder.AddInt(13, characterGearTier, 0); }
  public static void AddCharacterGearLevel(FlatBufferBuilder builder, int characterGearLevel) { builder.AddInt(14, characterGearLevel, 0); }
  public static Offset<FlatData.MiniGameDefenseFixedStatExcel> EndMiniGameDefenseFixedStatExcel(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<FlatData.MiniGameDefenseFixedStatExcel>(o);
  }
}


static public class MiniGameDefenseFixedStatExcelVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*MinigameDefenseFixedStatId*/, 8 /*long*/, 8, false)
      && verifier.VerifyField(tablePos, 6 /*Level*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 8 /*Grade*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 10 /*ExSkillLevel*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 12 /*NoneExSkillLevel*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 14 /*Equipment1Tier*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 16 /*Equipment1level*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 18 /*Equipment2Tier*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 20 /*Equipment2level*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 22 /*Equipment3Tier*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 24 /*Equipment3level*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 26 /*CharacterWeaponGrade*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 28 /*CharacterWeaponLevel*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 30 /*CharacterGearTier*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 32 /*CharacterGearLevel*/, 4 /*int*/, 4, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
