// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace FlatData
{

public enum ProductDisplayTag : int
{
  None = 0,
  New = 1,
  Hot = 2,
  Sale = 3,
  Limited = 4,
};


}
