// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace FlatData
{

public enum PurchaseCountResetType : int
{
  None = 0,
  Day = 1,
  Week = 2,
  Month = 3,
};


}
