// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace FlatData
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct RootMotionFlat : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static RootMotionFlat GetRootAsRootMotionFlat(ByteBuffer _bb) { return GetRootAsRootMotionFlat(_bb, new RootMotionFlat()); }
  public static RootMotionFlat GetRootAsRootMotionFlat(ByteBuffer _bb, RootMotionFlat obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public RootMotionFlat __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public FlatData.Form? Forms(int j) { int o = __p.__offset(4); return o != 0 ? (FlatData.Form?)(new FlatData.Form()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int FormsLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }
  public FlatData.Motion? ExSkills(int j) { int o = __p.__offset(6); return o != 0 ? (FlatData.Motion?)(new FlatData.Motion()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int ExSkillsLength { get { int o = __p.__offset(6); return o != 0 ? __p.__vector_len(o) : 0; } }
  public FlatData.Motion? MoveLeftOffset { get { int o = __p.__offset(8); return o != 0 ? (FlatData.Motion?)(new FlatData.Motion()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }
  public FlatData.Motion? MoveRightOffset { get { int o = __p.__offset(10); return o != 0 ? (FlatData.Motion?)(new FlatData.Motion()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }

  public static Offset<FlatData.RootMotionFlat> CreateRootMotionFlat(FlatBufferBuilder builder,
      VectorOffset FormsOffset = default(VectorOffset),
      VectorOffset ExSkillsOffset = default(VectorOffset),
      Offset<FlatData.Motion> MoveLeftOffsetOffset = default(Offset<FlatData.Motion>),
      Offset<FlatData.Motion> MoveRightOffsetOffset = default(Offset<FlatData.Motion>)) {
    builder.StartTable(4);
    RootMotionFlat.AddMoveRightOffset(builder, MoveRightOffsetOffset);
    RootMotionFlat.AddMoveLeftOffset(builder, MoveLeftOffsetOffset);
    RootMotionFlat.AddExSkills(builder, ExSkillsOffset);
    RootMotionFlat.AddForms(builder, FormsOffset);
    return RootMotionFlat.EndRootMotionFlat(builder);
  }

  public static void StartRootMotionFlat(FlatBufferBuilder builder) { builder.StartTable(4); }
  public static void AddForms(FlatBufferBuilder builder, VectorOffset formsOffset) { builder.AddOffset(0, formsOffset.Value, 0); }
  public static VectorOffset CreateFormsVector(FlatBufferBuilder builder, Offset<FlatData.Form>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateFormsVectorBlock(FlatBufferBuilder builder, Offset<FlatData.Form>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateFormsVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<FlatData.Form>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateFormsVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<FlatData.Form>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartFormsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddExSkills(FlatBufferBuilder builder, VectorOffset exSkillsOffset) { builder.AddOffset(1, exSkillsOffset.Value, 0); }
  public static VectorOffset CreateExSkillsVector(FlatBufferBuilder builder, Offset<FlatData.Motion>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateExSkillsVectorBlock(FlatBufferBuilder builder, Offset<FlatData.Motion>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateExSkillsVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<FlatData.Motion>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateExSkillsVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<FlatData.Motion>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartExSkillsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddMoveLeftOffset(FlatBufferBuilder builder, Offset<FlatData.Motion> moveLeftOffsetOffset) { builder.AddOffset(2, moveLeftOffsetOffset.Value, 0); }
  public static void AddMoveRightOffset(FlatBufferBuilder builder, Offset<FlatData.Motion> moveRightOffsetOffset) { builder.AddOffset(3, moveRightOffsetOffset.Value, 0); }
  public static Offset<FlatData.RootMotionFlat> EndRootMotionFlat(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<FlatData.RootMotionFlat>(o);
  }
}


static public class RootMotionFlatVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyVectorOfTables(tablePos, 4 /*Forms*/, FlatData.FormVerify.Verify, false)
      && verifier.VerifyVectorOfTables(tablePos, 6 /*ExSkills*/, FlatData.MotionVerify.Verify, false)
      && verifier.VerifyTable(tablePos, 8 /*MoveLeftOffset*/, FlatData.MotionVerify.Verify, false)
      && verifier.VerifyTable(tablePos, 10 /*MoveRightOffset*/, FlatData.MotionVerify.Verify, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
