// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace FlatData
{

public enum ScenarioModeSubTypes : int
{
  None = 0,
  Club = 1,
};


}
