// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace FlatData
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct ScenarioModeRewardExcel : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static ScenarioModeRewardExcel GetRootAsScenarioModeRewardExcel(ByteBuffer _bb) { return GetRootAsScenarioModeRewardExcel(_bb, new ScenarioModeRewardExcel()); }
  public static ScenarioModeRewardExcel GetRootAsScenarioModeRewardExcel(ByteBuffer _bb, ScenarioModeRewardExcel obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public ScenarioModeRewardExcel __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long ScenarioModeRewardId { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public FlatData.RewardTag RewardTag { get { int o = __p.__offset(6); return o != 0 ? (FlatData.RewardTag)__p.bb.GetInt(o + __p.bb_pos) : FlatData.RewardTag.Default; } }
  public int RewardProb { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public FlatData.ParcelType RewardParcelType { get { int o = __p.__offset(10); return o != 0 ? (FlatData.ParcelType)__p.bb.GetInt(o + __p.bb_pos) : FlatData.ParcelType.None; } }
  public long RewardParcelId { get { int o = __p.__offset(12); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public int RewardParcelAmount { get { int o = __p.__offset(14); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public bool IsDisplayed { get { int o = __p.__offset(16); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }

  public static Offset<FlatData.ScenarioModeRewardExcel> CreateScenarioModeRewardExcel(FlatBufferBuilder builder,
      long ScenarioModeRewardId = 0,
      FlatData.RewardTag RewardTag = FlatData.RewardTag.Default,
      int RewardProb = 0,
      FlatData.ParcelType RewardParcelType = FlatData.ParcelType.None,
      long RewardParcelId = 0,
      int RewardParcelAmount = 0,
      bool IsDisplayed = false) {
    builder.StartTable(7);
    ScenarioModeRewardExcel.AddRewardParcelId(builder, RewardParcelId);
    ScenarioModeRewardExcel.AddScenarioModeRewardId(builder, ScenarioModeRewardId);
    ScenarioModeRewardExcel.AddRewardParcelAmount(builder, RewardParcelAmount);
    ScenarioModeRewardExcel.AddRewardParcelType(builder, RewardParcelType);
    ScenarioModeRewardExcel.AddRewardProb(builder, RewardProb);
    ScenarioModeRewardExcel.AddRewardTag(builder, RewardTag);
    ScenarioModeRewardExcel.AddIsDisplayed(builder, IsDisplayed);
    return ScenarioModeRewardExcel.EndScenarioModeRewardExcel(builder);
  }

  public static void StartScenarioModeRewardExcel(FlatBufferBuilder builder) { builder.StartTable(7); }
  public static void AddScenarioModeRewardId(FlatBufferBuilder builder, long scenarioModeRewardId) { builder.AddLong(0, scenarioModeRewardId, 0); }
  public static void AddRewardTag(FlatBufferBuilder builder, FlatData.RewardTag rewardTag) { builder.AddInt(1, (int)rewardTag, 0); }
  public static void AddRewardProb(FlatBufferBuilder builder, int rewardProb) { builder.AddInt(2, rewardProb, 0); }
  public static void AddRewardParcelType(FlatBufferBuilder builder, FlatData.ParcelType rewardParcelType) { builder.AddInt(3, (int)rewardParcelType, 0); }
  public static void AddRewardParcelId(FlatBufferBuilder builder, long rewardParcelId) { builder.AddLong(4, rewardParcelId, 0); }
  public static void AddRewardParcelAmount(FlatBufferBuilder builder, int rewardParcelAmount) { builder.AddInt(5, rewardParcelAmount, 0); }
  public static void AddIsDisplayed(FlatBufferBuilder builder, bool isDisplayed) { builder.AddBool(6, isDisplayed, false); }
  public static Offset<FlatData.ScenarioModeRewardExcel> EndScenarioModeRewardExcel(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<FlatData.ScenarioModeRewardExcel>(o);
  }
}


static public class ScenarioModeRewardExcelVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*ScenarioModeRewardId*/, 8 /*long*/, 8, false)
      && verifier.VerifyField(tablePos, 6 /*RewardTag*/, 4 /*FlatData.RewardTag*/, 4, false)
      && verifier.VerifyField(tablePos, 8 /*RewardProb*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 10 /*RewardParcelType*/, 4 /*FlatData.ParcelType*/, 4, false)
      && verifier.VerifyField(tablePos, 12 /*RewardParcelId*/, 8 /*long*/, 8, false)
      && verifier.VerifyField(tablePos, 14 /*RewardParcelAmount*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 16 /*IsDisplayed*/, 1 /*bool*/, 1, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
