// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace FlatData
{

public enum StarGoalType : int
{
  None = 0,
  AllAlive = 1,
  Clear = 2,
  GetBoxes = 3,
  ClearTimeInSec = 4,
  AllyBaseDamage = 5,
};


}
