// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace FlatData
{

public enum StoryCondition : int
{
  Open = 0,
  Locked = 1,
  ComingSoon = 2,
  Hide = 3,
};


}
