// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace FlatData
{

public enum SubEventType : int
{
  None = 0,
  SubEvent = 1,
  SubEventPermanent = 2,
};


}
