// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace FlatData
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct WeekDungeonFindGiftRewardExcelTable : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static WeekDungeonFindGiftRewardExcelTable GetRootAsWeekDungeonFindGiftRewardExcelTable(ByteBuffer _bb) { return GetRootAsWeekDungeonFindGiftRewardExcelTable(_bb, new WeekDungeonFindGiftRewardExcelTable()); }
  public static WeekDungeonFindGiftRewardExcelTable GetRootAsWeekDungeonFindGiftRewardExcelTable(ByteBuffer _bb, WeekDungeonFindGiftRewardExcelTable obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public WeekDungeonFindGiftRewardExcelTable __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public FlatData.WeekDungeonFindGiftRewardExcel? DataList(int j) { int o = __p.__offset(4); return o != 0 ? (FlatData.WeekDungeonFindGiftRewardExcel?)(new FlatData.WeekDungeonFindGiftRewardExcel()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int DataListLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<FlatData.WeekDungeonFindGiftRewardExcelTable> CreateWeekDungeonFindGiftRewardExcelTable(FlatBufferBuilder builder,
      VectorOffset DataListOffset = default(VectorOffset)) {
    builder.StartTable(1);
    WeekDungeonFindGiftRewardExcelTable.AddDataList(builder, DataListOffset);
    return WeekDungeonFindGiftRewardExcelTable.EndWeekDungeonFindGiftRewardExcelTable(builder);
  }

  public static void StartWeekDungeonFindGiftRewardExcelTable(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddDataList(FlatBufferBuilder builder, VectorOffset dataListOffset) { builder.AddOffset(0, dataListOffset.Value, 0); }
  public static VectorOffset CreateDataListVector(FlatBufferBuilder builder, Offset<FlatData.WeekDungeonFindGiftRewardExcel>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateDataListVectorBlock(FlatBufferBuilder builder, Offset<FlatData.WeekDungeonFindGiftRewardExcel>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateDataListVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<FlatData.WeekDungeonFindGiftRewardExcel>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateDataListVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<FlatData.WeekDungeonFindGiftRewardExcel>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartDataListVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<FlatData.WeekDungeonFindGiftRewardExcelTable> EndWeekDungeonFindGiftRewardExcelTable(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<FlatData.WeekDungeonFindGiftRewardExcelTable>(o);
  }
}


static public class WeekDungeonFindGiftRewardExcelTableVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyVectorOfTables(tablePos, 4 /*DataList*/, FlatData.WeekDungeonFindGiftRewardExcelVerify.Verify, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
